### ISSUE TITLE
Membres modérateurs

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#1]
Si vous souhaitez vous ajouter comme membre **modérateur**, c'est ici !

**Comment by Frosty-Z** [comment]
Allez, tiens, je me propose :-)
Dans un premier temps je ne traiterai que des trucs "évidents" (orthographe etc.), je ne perturberai pas par ex. l'organisation des docs, l'architecture de base de l'éventuel outil open source à développer, etc.

**Comment by sveinburne** [comment]
Done ;)

**Comment by sveinburne** [comment]
@fsamin, ça te tente ?

**Comment by sveinburne** [comment]
Effectivement ! j'pense qu'on a tous du travail à côté, sans compter les événements récents... mais en s'investissant régulièrement, même un petit peu, c'est déjà bien cool !

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#19
