### ISSUE TITLE
Langage de programmation

### ISSUE THREAD

**Issue by akrib** [sveinburne/lets-play-science#12]
Bonjour,
La question du langage de programmation doit selon moi faire partie du cahier des charges. 
pour ma part je peux aider sur des technologies web. (SGBD, JAVA, PHP, AJAX, HTML5).

Pour ma part je souhaite évoquer l'idée, d'un jeu ludique et participatif, comme l'évoque prof Okita dans le 'Postulat #1' 
https://www.youtube.com/watch?v=raa4Lds9aTM

Par exemple en utilisant le système de 'Twitch Play Pokémon'  ou l’écriture mot par mot ce ferait en utilisant le mot le plus utilisé par la communauté.

**Comment by Frosty-Z** [comment]
Salut, je peux intervenir à peu près sur les mêmes technos web, créer des éléments graphiques...

Pour ce qui est de l'aspect ludique, je ne pense pas qu'il soit nécessaire ou utile d'aller jusqu'à une expérience d'écriture mot à mot, mais c'est sûr que même si on reste sur un ensemble interfaces assez classiques de type "travail collaboratif" (vote social, fils de discussion, etc.), plus c'est ludique et accessible, mieux c'est.

**Comment by Frosty-Z** [comment]
Cette discussion devrait avoir le tag "enhancement" mais soit je suis pas doué avec github, soit j'ai pas les droits pour le faire :-)

**Comment by sveinburne** [comment]
Sur les technos, je pense que c'est important mais pas immédiatement... On peut déjà, dans le cahier des charges, référencer des librairies JS qui peuvent répondre à un besoin, comme d3.js pour les mind maps. Ensuite se posera la question de la base de données : SQL ou NoSQL, puis du langage serveur etc... Je suis très favorable à Node.js perso, ou un framework super intégré comme **Meteor.js**... Mais mon avis demeure biaisé, j'ai jamais codé autre chose côté serveur que J2EE ou Node... J'ai un a-priori négatif sur Php, mais ça reste un a-priori... En tout cas, je pense qu'on peut attendre avant de parler de technos / frameworks d'un point de vue macro, et se contenter des librairies client qui répondent directement à un besoin? La raison est qu'on a pas encore assez de recul, et que je souhaite pas qu'on mette la charrue devant les bœufs. **Par contre**, un inventaire des technos maitrisées par chacun, ça a de la valeur. ( cf 875f5159a88abab75699631922d84ef22692d6b3 )

**Comment by sveinburne** [comment]
Sur l'expérience d'écriture, je rejoins Frosty-Z. Mais la réflexion sur l'aspect ludique mérite un topic à part, je vous laisse l'initiative de le lancer !

**Comment by fsamin** [comment]
Les technos ne peuvent pas faire partie du cahier des charges, elles doivent découler des choix logiques en fonction des problématiques à aborder coté client, comme coté serveur - prenant en compte l'expérience utilisateur, la maintenabilité, l'hébergement, etc...

Le choix du framework JS et des assets coté client, le choix le langage coté serveur : il sera temps de voir ça plus tard. Ceci dit après avoir codé du **Java/JEE** depuis 2000, avoir fait un peu de **NodeJS**, je passe progressivement au **Go (golang)** et j'en suis très heureux :smile:

**Comment by sveinburne** [comment]
@fsamin, @Frosty-Z, @Roxtarmy merci de faire [une PR sur ce fichier](https://github.com/sveinburne/lets-play-science/blob/master/CONTRIBUTEURS.MD) !
