### ISSUE TITLE
License / Droits d'utilisation du contenu de ce projet Github

### ISSUE THREAD

**Issue by fsamin** [sveinburne/lets-play-science#15]
Je serais pour qu'on indique la license et les droits d'utilisation de ce qui est créé ici.
Je propose :
 - http://creativecommons.org/licenses/by-nc/4.0/

La discussion est ouverte

**Comment by sveinburne** [comment]
+1 !
Commercial / Non Commercial ? 
Je serais tenté par NC, qu'en pensez-vous ?

**Comment by Frosty-Z** [comment]
+1

**Comment by ranska** [comment]
+1

**Comment by Aelerinya** [comment]
+1

**Comment by sveinburne** [comment]
@fsamin, je crois que ça fait "l'unanimité", tu peux t'en occuper ?

**Comment by fsamin** [comment]
:+1:

**Comment by sveinburne** [comment]
:+1: lol ^^

**Comment by sveinburne** [comment]
**PR** en cours d'élaboration #63
