### ISSUE TITLE
Réputation

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#17]
Je reprends l'interrogation de @akrib et la remarque de @Frosty-Z pour en faire un post 

> le truc bien ludique et entraînant sur StackOverflow (+ tous les sites sur le même modèle type StackExchange) et qui a certainement contribué à son succès, c'est le système de **réputation** qui donne accès à des fonctionnalités avancées / de modération pour les membres les plus actifs proposant des réponses pertinentes, en plus d'afficher aux autres participants qu'on est un membre reconnu qui s'est investi (= de confiance).

**Comment by sveinburne** [comment]
Je trouve ça pertinent : c'est finalement un accès progressif et mérité à la modération ! On évite ainsi le piège d'une structure trop verticale.

**Comment by ranska** [comment]
c'est pas justement verticale l'assention au post admin par la colecte de point.
A mon avis une stratification meme mineur et toujours un phénome émérgeant.
Ce que j'aime dans ce débat c'est qu'il est plein de rebondissement :)

**Comment by Frosty-Z** [comment]
Oui ça devient vertical, mais si "ceux d'en haut" sont plébiscités par "ceux d'en bas", c'est déjà beaucoup moins gênant qu'un fonctionnement où "ceux d'en haut" sont autoproclamés (modération d'un forum, médias mainstream... même un projet github :wink: )
D'ailleurs sur StackOverflow ils poussent la logique de vote jusqu'à faire élire les modos chaque année : http://stackoverflow.com/election ; je trouve que c'est top !

**Comment by sveinburne** [comment]
J'ai créé une nouvelle branche **the_app_2** avec un gros refactoring des définitions (qui étaient trop "partisanes" et incomplètes jusqu'ici) + la proposition des Vues d'Ensemble, cf #26 . Notamment une section [**politique**](https://github.com/sveinburne/lets-play-science/blob/the_app_2/THE_APP.MD#3-politique) dans laquelle on retrouve ce débat sur la modération, je pense que l'utilisation du vocabulaire opportun peut aider ;)

**Comment by Frosty-Z** [comment]
@sveinburne Pour ma part ça me va très bien ce que tu as fait dans **the_app_2** pour le fichier `THE_APP.MD` :+1: 
En relisant, j'ai juste fait un petit commit orthographe / mise en forme.

:arrow_forward: +1 pour merger dans **master**.

**Comment by Frosty-Z** [comment]
@sveinburne Bon j'ai fait une proposition de [**VE** dans la branche **the_app_2**](https://github.com/sveinburne/lets-play-science/blob/the_app_2/VE/VE-Frosty-Z.MD). Si ça te va, je peux créer une "issue" spécifique à cette **VE**.
Si j'ai le temps dans la semaine je ferai de la veille Youtube/Facebook ; dans ce cas je compte faire une synthèse dans une nouvelle issue **"Revues Youtube"** avant d'aller toucher le `Readme`.
