### ISSUE TITLE
Priorités ?

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#21]
Juste pour éviter qu'on parte un peu dans tous les sens...

En fait sur quoi devrait-on se focaliser en priorité ? J'ai l'impression que le suggestions et propositions affluent, que ce soit dans le `Readme`, dans `THE_APP` ou les "issues", mais rien ni personne n'indique vers quoi nous devrions "tendre", vers quels points particuliers il faudrait se concentrer.

On est un peu comme dans *"Twitch plays Pokémon"*, dans la version "brute" où chaque appui de touche est pris en compte.

D'autant que bon, il n'y a pas de "deadline", c'est un sujet fun où chacun peut contribuer un peu comme il veut, ce qui grandit d'autant plus le risque de trop se disperser et donc arriver rapidement à un gros fouillis insondable.

Je ne sais pas vous, mais pour ma part j'ai eu des envies frénétiques de **voter** pour aider à donner des directions plus claires, notamment en lisant les sections **II.** et **III.** du `Readme`, comme si c'étaient des questions de site Q&A du genre :

* (pour le II.) **Quelles fonctionnalités devraient avoir l'outil d'aide à la collaboration pour "Let's play science" ?** => Par le vote, on verra émerger rapidement les fonctionnalités prioritaires qu'il faut rechercher sur un outil existant, ou bien "notre" outil open source (en imaginant qu'on a un délai relativement court pour le développer et qu'il faut alors "assurer l'essentiel").

* (pour le III.) **Quel outils/services existants aideraient à collaborer à une question de "Lets play science" ?** => même type de réflexion.

Et on se retrouverait (en gros) dans le cas de *"Twitch plays Pokémon"* où les participation votent pour la direction à prendre le coup suivant...

Du coup j'ai créé 2 questions sur Tricider (oui je l'aime bien celui ça :wink: ) : 
* [Outil collaboratif Let's play science : de quelles fonctionnalités doit-il disposer ?](http://www.tricider.com/brainstorming/34O75F4FgG7) [(lien admin)](https://www.tricider.com/admin/34O75F4FgG7/CN8kK1IcbOt)
* [Quel outils/services existants aideraient à collaborer à une question de "Lets play science" ?](http://www.tricider.com/brainstorming/2kR2A9QuQLR) [(lien admin)](https://www.tricider.com/admin/2kR2A9QuQLR/6XC6fCOD7p)

On verra bien ce que ça donne... Pour plus de visibilité il faudrait que je mette ces liens dans un commentaire Youtube, qu'en pensez vous ?

Ca pourrait aussi nous aider pour d'autres décisions, telles que le choix de techno si on se lance dans du dev, sans que ça se termine en "flame wars" genre Java vs. PHP avec une multitude de points Godwin dans une discussion de forum :smile:

**Comment by sveinburne** [comment]
Très bonne initiative... Je pense juste qu'il faudrait une plus grande granularité, j'veux dire surtout pour la **II**, les sous-propositions. Car certaines sous-propositions représentent un "cout" de développement beaucoup plus grand, comme une analyse sémantique statistique. A contrario, certaines propositions coûteraient cher à ne pas intégrer dans le développement tout de suite. Ma vision des choses : dans un premier temps, on sera amené à utiliser une plateforme existante ( tricider et authorea ont l'air d'être de bons candidats, quitte à les jumeler ). Et en parallèle on continue à spécifier l'application, jusqu'à arriver à un moment ou une certaine stabilité des specs est atteinte ( **ce qui comprend l'ordre des priorités que tu soulève** ). A ce moment là, on essaie de mobiliser la communauté open source, je pense que ce projet est assez inédit et qu'il pourrait mobiliser au delà des amateurs de LetsPlayScience.

**Comment by Frosty-Z** [comment]
Voilà, les liens sont posés dans le ˋReadmeˋ et dans les commentaires Youtube (en réponse au commentaire de Léo sur ce repo github). J'espère que ça portera ses fruits :sunglasses: 

Pour les sous-propositions, je compte créer des "Questions Tricider" (QT) pour
* II.3 Association sémantique des posts
* II.5 Une interface qui favorise l'évaluation entre pairs

et mettre les liens vers les QT dans le ˋReadmeˋ + dans les propositions de la QT déjà créée pour la section **II**. @sveinburne ça conviendrait ?

**Comment by Frosty-Z** [comment]
Gros bugs avec les commentaires sur les interfaces Youtube pour mobiles et tablettes (que ce soit via appli ou site web)... Du coup, ça y est, les liens vers les QT sont posés sur Youtube.

**Comment by fsamin** [comment]
Je ne connaissais pas Tricider. C'est assez instable ou ça vient de moi ?

**Comment by Frosty-Z** [comment]
@fsamin Concernant Tricider, depuis ma tablette c'est lent à réagir, du coup des fois je "clique" 2 fois au lieu d'une et ça envoie vers une page d'erreur :-1: 

Depuis mon PC c'est mieux, par contre pour ce qui est de la création d'un compte avec Google+ ou leur propre système, ça n'a jamais fonctionné (avec Google+ ça reste bloqué sur la fenêtre d'autorisation de Google, et avec leur propre système je n'ai jamais reçu le mail de validation) :-1:

Malgré tout c'est gratuit, disponible pour tout le monde immédiatement sans dev/install/config d'aucune sorte, on peut y créer des questions et y participer sans s'inscrire, et le fait de pouvoir lister les arguments pour/contre est sympa. :+1: :+1: :+1:  Du coup n'ayant pas trouvé mieux après 1/2h de recherche, je suis parti là dessus :wink:

**Comment by sveinburne** [comment]
@Frosty-Z  excuse moi d'avoir tardé à réagir, beaucoup de taff !! Oui ça me va :)

**Comment by ranska** [comment]
J'ai du mal à identifier au ce projet veux en venir ?
Parlons nous dans un 1er temps de but ou d'outils ?

**Comment by Frosty-Z** [comment]
D'après ma compréhension, pour le moment on cherche à faire l'inventaire des fonctionnalités nécessaires, ensuite on voit si un outil existant correspond à peu près à cet ensemble de besoins, sinon on essayera de développer un outil spécifique ici même s'il y a assez de contributeurs.
Cf. ˋReadme.mdˋ

**Comment by Frosty-Z** [comment]
@sveinburne des Questions Tricider ont été créées pour II.3 et II.5, les liens (+ liens admin) ajoutés dans le `Readme`.

**Comment by ranska** [comment]
@Frosty-Z merci de ta réponse.
Quel est le but, besoin 1er à satisfaire ? En ce basant sur les réussite majeur du web, 
la stratégie de démarer avec un minimu de fonctionalités puis itérer peu etre un bon début.

**Comment by Frosty-Z** [comment]
@ranska C'est l'objet de cette [question Tricider](http://www.tricider.com/brainstorming/34O75F4FgG7) à laquelle je t'invite à participer (voter, ajouter des propositions, des arguments).

Cela dit j'ai un peu foiré le truc puisque j'ai mis directement les propositions du point **II.** du `Readme` qui concernent surtout un "espace" ou une "plateforme" de discussion (type Discourse et/ou directement les commentaires Youtube/FB) alors que j'aurais dû faire une "sous question" pour ça, comme je disais dans une autre "issue".

Du coup je pense qu'il va falloir que je transforme cette [question Tricider](http://www.tricider.com/brainstorming/34O75F4FgG7) en sous-question ciblée "espace de discussion" (en retirant les propositions "hors sujet"), puis que je crée une nouvelle "question principale" qui reprendrait par exemple les propositions de différents "espaces" (discussion classique, écriture collaborative, Q&A, rapport/metrics, etc).

**Comment by Frosty-Z** [comment]
@ranska Voici la nouvelle question Tricider : [Collaboration pour Let's play science : de quels outils et fonctionnalités générales a-t-on besoin ?](http://www.tricider.com/brainstorming/2vvPwC7VeKt).

**Comment by sveinburne** [comment]
Plus d'activité ici, mais un méta-topic pour les votes pourrait être le bienvenu !
