### ISSUE TITLE
Organisation du projet

### ISSUE THREAD

**Issue by fsamin** [sveinburne/lets-play-science#26]
Pour aller plus loin que l'issue #21, j'en arrive à me dire que le projet github n'est pas assez structuré.
Je proposerai donc que les fichier sur la branche master ne soit que ce qui est "validé" par un minimum de contributeurs (3, 5, 10, 1000, ...)

Les ajouts/modifications/suppression du contenu de ces projets devrait passé par des PR pour lesquelles le merge ne pourrait être fait qu'après "validation" ou "revue".  Sur le projet [docker/docker](https://github.com/docker/docker), il faut 5 LGTM ("looks good to me") pour qu'une PR soit mergée.

Les échanges, les votes, les avantages et inconvénients de chaque proposition pourraient se faire au sein des commentaires des PR.

Il faudrait également découper le contenu du readme en plusieurs fichiers.

Je vous invite à lire https://github.com/docker/docker/blob/master/CONTRIBUTING.md pour voir comment un gros projet open-source arrive à l'organiser. Sans allez aussi loin, on peut s'inspirer de la manière dont ils gèrent la doc.

L'avantage de tout ça serait qu'à un instant *t*, le contenu du master serait l'état de ce que la communauté a décidé à la majorité. Je suis conscient que ça change l'orientation actuelle du projet, mais j'ai peur qu'on se perde un peu dans une longue liste de propositions disjointes sans ce mettre d'accord entre nous ce qui nous semble pertinent ou non.

Pour en discuter.

**Comment by sveinburne** [comment]
Je comprends tout à fait ta préoccupation. Je pense qu'un LGTM est une bonne idée, à condition qu'il y ait suffisamment de participants et modérateurs... Mon avis : le projet est encore trop petit et immature pour qu'on ai besoin d'une telle politique. 
Aussi il ne faudrait pas se précipiter. 
- D'une part, car tant que Léo n'a pas fait sa propre synthèse, on ne peut pas se permettre de prendre les devants. 
- D'autre part, car pour le moment des idées circulent encore depuis youtube, **il faudrait d'ailleurs organiser une veille là dessus**. 

Le but de ce projet est d'avant tout montrer à Léo qu'on peut se mobiliser et travailler ensemble! 
Sur tes craintes légitimes que les spécifications se dispersent, je commence à me dire que **chaque proposant qui souhaite soumettre une vision d'ensemble cohérente de son application idéale** devrait peut être la soumettre sous forme d'un MD  qui suit une structure bien définie, dans lesquelles la personne doit définir, à minima : 
- les termes qu'elle utilise 
- le cycle de vie d'un défi 
Car je me suis rendu compte qu'on avait pas forcément tous la même application en tête, et que si chacun d'entre nous qui a une vision d'ensemble la posait clairement à l'écrit, on pourrait déjà mieux se comprendre. Car le problème d'un vote proposition par proposition, c'est que ça ne forme pas un tout cohérent. 
Plus tard on pourra faire une synthèse lisible des différentes approches qui émergent. Enfin, ça reste que mon humble point de vue...

**Comment by ranska** [comment]
LGTM 
dans tout projet open source la branche master et celle qui fait référence (pour etre forker utiliser ou citer).
Meme si c'est un projet text, il me semble pertinent de fonctionner comme tout projet standar qui utilitse dès jour 0 les bonnes pratiques.

**Comment by Frosty-Z** [comment]
Concernant la politique de validation, pour le moment je trouve qu'on en fait déjà assez, il faudra attendre d'être plus nombreux et actifs pour se reposer ces questions, ce qui rejoint l'avis de @sveinburne.

Pour la **veille Youtube**... C'est un gros boulot, que Léo va faire de toute façon à un moment donné. A l'occasion, j'essayerai de lire "en diagonale" les commentaires récents pour essayer de repérer les grandes tendances, et si je vois des nouveautés flagrantes je ferai une ou plusieurs PR sur le Readme afin d'en tenir compte.

Concernant le fait de pouvoir **soumettre des MD de propositions cohérentes**, je suis partant, mais en indiquant qu'il faudra rester aussi concis que possible. Mais ça va obliger quelqu'un à repasser derrière pour faire la synthèse de tout ça et (encore une fois) tenir compte des idées qui reviennent le plus souvent.

Cela dit, je pense qu'un **vote par proposition** a toutes les chances de donner un ensemble cohérent au final, mais je pense que j'ai foiré la question correspondant au **II.** du `Readme`, car les propositions sont déjà très orientées *"fil de discussion/commentaires"* (notion de posts). J'aurais dû directement créer une sous question pour détailler les fonctionnalités souhaitables spécifiques au principe de *forum / fil de discussion*.

En fait les propositions correspondant au **II.** (trouver/créer un outil qui dispose de...) devraient plutôt être du style :
* **Espace forum / fil de discussion ou de commentaires** (Youtube, Facebook ou fait maison)
* **Espace d'écriture collaborative** (Etherpad, Wiki, Github+PR ou fait maison)
* **Espace Q&A** (Tricider ou [autre](http://web.appstorm.net/roundups/18-awesome-survey-poll-apps/) ou fait maison)
* **Espace "rapport/metrics"** (résultats d'analyses automatiques des divers espaces collaboratifs, occurences de mots clés, tags, génération de mind map ou autre...)
* etc.

Au passage ce que je viens de lister commence à ressembler à une "proposition cohérente" que je pourrais formuler sous forme de MD ; resterait à prioriser les divers espaces et les fonctionnalités de chacun de ces espaces (et là je dirais : on vote).

**Comment by sveinburne** [comment]
**Proposition (je préfère l'appeler *vision d'ensemble* pour ne pas tromper les lecteurs) cohérantes par MD** 
- Certaines définitions seront communes à toutes les visions d'ensemble (**VE**), donc on conservera le THE_APP.MD en expliquant la logique en cours de réalisation. 
- Dans ce fichier THE_APP.MD 
   - on explique la démarche pour soumettre une VE
   - on répertorie les VE publiées dans le dossier visions
   - on insiste sur le fait qu'une nouvelle VE doit être sensiblement différente d'une VE existante pour être validée. 
    - on propose la possibilité d'amender une VE et d'en discuter dans une issue maintenue par son premier auteur. 

**Vote par proposition**
Je te rejoins : si tu souhaites proposer une restructuration dans une nouvelle branche, on pourra revenir à toi avant de merger ! Je tiens à signaler que j'ai structuré ça un peu à la hâte et que je n'avais pas à l'esprit une solution à mi-chemin suivant les composantes considérées, c'est donc totalement pertinent. 

**Veille** 
Sur la veille, ouai faudrait qu'à tour de rôle on fasse un tour... c'est pas idéal mais ça serait dommage de passer à côté de pépites ! Bien relire le README.md pour avoir à l'esprit l'ensemble des propositions existantes.

**Comment by Frosty-Z** [comment]
@sveinburne Ok pour les VE :+1: . J'attends les instructions et le feu vert pour soumettre la mienne :wink: 

Pour le **II.** du `Readme` j'essaierai de proposer une petite restructuration dès que je peux par une PR que je te laisserai le soin de vérifier.

Pour la veille, je propose que le premier qui a du temps pour repasser sur les 375+ commentaires Youtube (ou même une petite partie) se manifeste aux autres. Peut être mettre dans un fichier à part genre `Revue_commentaires_Youtube.md` le nombre de commentaires déjà revus, histoire qu'on ne fasse pas le boulot depuis le début en double ou triple...

**Comment by sveinburne** [comment]
@Frosty-Z sur la branche [the_app_2](https://github.com/sveinburne/lets-play-science/blob/the_app_2/THE_APP.MD#I.1) tu vas pouvoir suivre les consignes explicitées en **II** ! Je vais être indisponible tout le week end jusque mardi, donc je te fais suffisamment confiance pour prendre les devants et expliciter la démarche dans `README.md` :)
Au sujet de la veille, je suis totalement d'accord, là aussi je te laisse l'initiative si tu veux bien / as le temps ! Sur ce, va m'coucher ...

**Comment by fsamin** [comment]
@sveinburne @ranska @Frosty-Z Je n'ai pas trop eu le temps de suivre, ni de vous lire ces derniers jours. Je regarde tout ça ce week end.

**Comment by Frosty-Z** [comment]
@sveinburne
- Une PR est créée pour la petite réorganisation du `Readme`, merci de voir si ça te va
- J'ai remanié les questions Tricider comme indiqué dans mon message précédent. Une nouvelle question Tricider a donc vu le jour : [Collaboration pour Let's play science : de quels outils et fonctionnalités générales a-t-on besoin ?](http://www.tricider.com/brainstorming/2vvPwC7VeKt). J'ai modifié mon commentaire Youtube pour pointer vers cette nouvelle question, les liens côté `Readme` aussi, etc.

Reste à rédiger et soumettre ma VE (ce week-end peut être), puis si le temps me le permet, faire de la veille Youtube (sans oublier Facebook)...

**Comment by sveinburne** [comment]
@fsamin @Frosty-Z :+1: Je suis absent ce WE, mais je reviens sur le github mardi ! Faudra une fois que les questions Tricider sont stabilisées qu'on fasse un +1 sur ton post youtube pour faire le faire émerger...
