### ISSUE TITLE
Utiliser le système de issue ?

### ISSUE THREAD

**Issue by marcbal** [sveinburne/lets-play-science#3]
Peut-être devrais-tu privilégier le système de Issue plutôt que de proposer aux gens de remplir le fichier readme. Cela mettra au profit le système de commentaire des Issues, un filtrage par exemple pour les commentaires haineux (je pense qu'ils seront rare ici ^^ ), le système de Labels aussi, qui peut servir à trier. On pourra facilement voir les idées sous forme de titre (liste des issues) concernant l'élaboration/recherche du futur système collaboratif pour nos futurs lets-play-science.

Je sais que tu propose le système de Issue en introduction, mais tu indique une préférence pour l'édition du Readme, qui pour moi est moins pratique pour l'organisation.

Un autre moyen serai aussi de permettre la création d'autres fichiers dans le dépôt, permettant une organisation en différents documents. De préférence en .md, bien sûr. (je préfère cependant ma première idée)

**Comment by sveinburne** [comment]
L'avantage pour les pull request, c'est qu'un fil de discussion peut s'y associer, c'est quand même plus rapide. Mais bon, je peux peut-être mettre "à égalité" les deux options ?

**Comment by sveinburne** [comment]
J'ai fais un commit pour prendre en compte tes commentaires, qu'en dis-tu, je t'ai bien compris ^^?

**Comment by marcbal** [comment]
C'est très bien comme ça, merci ;)
