### ISSUE TITLE
Propositions de Inspiration & Recherches

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#32]
Ce topic permet de référencer des **pistes de recherche** avant de les intégrer dans [INSPIRATION.MD](https://github.com/sveinburne/lets-play-science/blob/master/THEORIE/INSPIRATION.MD).

Pour discuter de l'organisation du document, **allez sur l'issue #38**

**Des pistes de recherche :**
- Celui qui m'est directement venu à l'esprit, je l'ai découvert lors d'un MOOC sur les ressources éducatives libres. 
Il s'agit de **Stephen Downes** et ses recherches sur le [**connectivisme**](https://fr.wikipedia.org/wiki/Connectivisme) : une vision de l'apprentissage à l'aire des nouvelles technologies, juste en plein dans le mile pour notre projet! 
- La [Cybernétique](https://fr.wikipedia.org/wiki/Cybern%C3%A9tique) est une discipline transdisciplinaire qui vise à l'étude des phénomènes organiques et émergents au contact de l'homme et de la machine. Plus abstraite, au croisement de la philosophie et de la technique mais il me semble tout à fait pertinente.

**Comment by Frosty-Z** [comment]
Je viens de découvrir le principe des **MOOC**, c'est impressionnant l'ampleur que ça a pris.
En fait j'ai déjà suivi quelques *cours en ligne* donnés par Adobe France il y a quelques années avec une poignée de participants, en me doutant que le principe avait certainement été repris à plus grande échelle, mais ne m'y étais jamais vraiment intéressé plus que ça. De plus nous n'avions pas été confrontés à des problématiques de *travail collaboratif* (ce qui nous intéresse vraiment ici).

En cherchant un peu, je suis tombé sur une lecture intéressante (pas au niveau d'une étude scientifique mais bon) : problématiques rencontrées avec un outil qui combine plateforme d'écriture collaborative + T'chat, un certain [framapad](https://framapad.org).
Voir : [Synthèse MOOC ITYPA](https://docs.google.com/document/d/16bkqQ0MT2zF7PaepadjC4-UvNSluQXCRrVf82Kj_QZU/mobilebasic#)

Le temps me manque mais à l'occasion je compte bien faire d'autres petites recherches.

**Comment by gossetj** [comment]
Pour les inspirations, j'ai pensé à:
- la **robotique collective**, qui consiste à coordonner et synchroniser des robots entre eux afin qu'ils remplissent une tâche unique, que l'on aura en général divisé en sous-objectifs appliqués à chaque robot. Cette robotique s'appuie de plus en plus aujourd'hui sur la **simulation multi-agent**, qui consiste en l'étude de systèmes complexes par simulations de ceux-ci en modèle comportant différents agents distincts. Je pense que ces deux disciplines sont prometteuses et peuvent mettre en avant des aspects pratiques liés à la colaboration en général.
- la **sociologie, la psychologie et la philosophie**, notamment mis en avant par les chaînes youtube **horizon-gull** et **La Tronche en Biais**, qui, je pense, offrent une vue plus centrée sur l'humain et ses interactions, et donc des concepts de colaboration plus proche des mécanismes humains.
- la programmation parallèle, qui consiste à gérer plusieurs coeurs de processeurs pour qu'ils se partagent de manière optimale les tâches et calculs donnés. Celle-ci utilise notamment un concept très simple: est-ce qu'on peut paralléliser la tâche? est-ce utile de parralléliser cette tâche? Ce qui en somme, consiste à distinguer les étapes de déroulement du programme pour sélectionner les parties optimisables et éviter les optimisations "négatives".

**Comment by Frosty-Z** [comment]
@gossetj :+1: +1 notamment pour : **simulation multi agent**, **psychologie**, **sociologie** (et donc [psychologie sociale](https://fr.wikipedia.org/wiki/Psychologie_sociale)), l'analogie avec certains aspects de la **programmation parallèle**.

Tu veux bien faire une PR pour proposer d'intégrer ces idées d'inspiration au fichier `INSPIRATION.MD` ?

**Comment by gossetj** [comment]
Il me semble que PR désigne le bouton pull request, mais je ne vois pas bien comment compléter la procédure. J'ai vu qu'on pouvait forker le repo pour le modifier dans son coin et proposer la modif avec le pull request, est-ce de celà que tu me parles?

**Comment by Frosty-Z** [comment]
Bon il va être temps que je bosse sur ce fameux tuto ! :wink: 

Cela dit @sveinburne a déjà écrit la procédure à suivre assez précisément ici : https://github.com/sveinburne/lets-play-science/blob/master/SYNTHESE.MD#I.2

Normalement pas besoin de forker le repo, ça fait une branche toujours dans celui ci (en tout cas avec les droits que j'ai sur le projet). Mais les deux techniques (pull request via un fork du repo vs. pull request via une branche dans le repo lui-même) doivent fonctionner.

**Comment by sveinburne** [comment]
@gossetj @Frosty-Z, je vais nettoyer un peu cette issue pour qu'on reste sur les propositions !
@gossetj tu pourrais ptet te mettre [sur gitter](https://gitter.im/sveinburne/lets-play-science), ça sera plus simple pour communiquer. J'ai bien vu tes commits ; le mieux je pense serait que tu proposes d'abord une restructuration [dans le topic dédié](https://github.com/sveinburne/lets-play-science/issues/38) #38, j'aimerais autant que ce topic ne serve qu'aux pistes de recherche! Je supprimerais mon commentaire une fois ta proposition soumise.

**Comment by sveinburne** [comment]
@gossetj Merci pour cette **PR** ! 
- Une initiative sociale, les [Réseaux d'Echange Réciproque de Savoirs](https://fr.wikipedia.org/wiki/R%C3%A9seau_d'%C3%A9changes_r%C3%A9ciproques_de_savoirs)
- Une pratique, le [**management**](https://fr.wikipedia.org/wiki/Management)
- Une pratique, [**la méthode agile**](https://fr.wikipedia.org/wiki/M%C3%A9thode_agile)

**Comment by sveinburne** [comment]
Le [**forage de données**](https://fr.wikipedia.org/wiki/Exploration_de_donn%C3%A9es) ou *data mining* qui a déjà été suggéré dans SYNTHESE.MD lorsqu'on a parlé d’analyse statistique. Le forage de données, c'est la recherche de **connaissances** à partir d'une grande quantité de données produites par un groupe, une activité, une communauté.  Nous sommes en plein dans l'**élaboration du savoir**.

**Comment by sveinburne** [comment]
[Un article sur l'apprentissage collaboratif publié par l'université de Vanderbilt](https://cft.vanderbilt.edu/guides-sub-pages/teamcollaborative-teaching/), j'ai pas eu le temps de creuser mais ça peut valoir le détour.

**Comment by fsamin** [comment]
Pour rebondir sur la fouille de données cité par @sveinburne:

 [lien wikipedia](https://fr.wikipedia.org/wiki/Exploration_de_donn%C3%A9es)

Il y a une partie "methodologique" assez interessante et notamment ce tableau, qui met en évidence, je trouve, les enjeux et objectifs de l'intelligence collective.

<table class="wikitable sortable centre jquery-tablesorter">
<caption><b>Estimation du temps à consacrer aux différentes étapes</b><sup id="cite_ref-tuff44_51-0" class="reference"><a href="https://fr.wikipedia.org/wiki/Exploration_de_donn%C3%A9es#cite_note-tuff44-51"><span class="cite_crochet">[</span>b 3<span class="cite_crochet">]</span></a></sup><sup class="reference cite_virgule">,</sup><sup id="cite_ref-52" class="reference"><a href="https://fr.wikipedia.org/wiki/Exploration_de_donn%C3%A9es#cite_note-52"><span class="cite_crochet">[</span>44<span class="cite_crochet">]</span></a></sup></caption>
<thead><tr>
<th scope="col" tabindex="0" class="headerSort" role="columnheader button" title="Tri croissant"><b>Tâches</b></th>
<th scope="col" tabindex="0" class="headerSort" role="columnheader button" title="Tri croissant"><b>Charge</b></th>
<th scope="col" tabindex="0" class="headerSort" role="columnheader button" title="Tri croissant"><b>Importance<br>
dans le projet</b></th>
</tr></thead><tbody>
<tr>
<td>Inventaire, préparation et exploration des données</td>
<td>38&nbsp;%</td>
<td>3</td>
</tr>
<tr>
<td>Élaboration - Validation des modèles</td>
<td>25&nbsp;%</td>
<td>2</td>
</tr>
<tr>
<td>Restitution des résultats</td>
<td>12&nbsp;%</td>
<td>4</td>
</tr>
<tr>
<td>Analyse des premiers tests</td>
<td>10&nbsp;%</td>
<td>3</td>
</tr>
<tr>
<td>Définition des objectifs</td>
<td>8&nbsp;%</td>
<td>1</td>
</tr>
<tr>
<td>Documentation - présentations</td>
<td>7&nbsp;%</td>
<td>5</td>
</tr>
</tbody><tfoot></tfoot></table>

Je trouve que le premier point est déjà bien abordé, mais les autres assez peu. Par exemple : 
 - La définition des objectifs de la recherche que nous avons appelé __défi__ a été assez peu abordé. Est-ce que *Comment collaborer à 5000 cerveaux sur la même question ?* constitue un objectif assez précis ?
 - Comment pourrait-on valider des modèles ? Comment Léo peut-il estimer que la collaboration issue des 5000 cerveaux atteint (ou pas) ses objectifs ? Si on reprend l'exemple de "twitch plays pokemon", la collaboration doit aboutir a un avancement dans le jeu, mais comment mesurer un avancement dans une reflexion collaborative. C'est un problème récurrent avec toutes les pratiques d'intelligence artificielle qui nécessite l'évaluation d'une "santé" qui permet de valider un modèle... L'article [wikipedia sur l'intelligence collective](https://fr.wikipedia.org/wiki/Intelligence_collective) apporte des éléments de reflexion complémentaires par rapport à l'importance de la __valorisation__ de cette intelligence collective, il serait intéressant de mettre en lien cette __valorisation__ avec la __validation des modèles/analyses de tests__ mis en oeuvre dans une processus de fouille de données. 

désolé, je m'emballe un peu... :sweat_smile:

**Comment by fsamin** [comment]
Avez-vous entendu parlé du Conseil National du Numérique qui a lancé plusieurs __Consultations__ sur des thèmes de sociétés en lien avec le numérique ?

Le Conseil National du Numérique (en tant qu'entité organisatrice) propose une consultation par exemple : `Economie collaborative : Poser un cadre pour le développement de l’économie du partage`

Cette consultation est assez détaillée par une une `présentation des enjeux`

Ensuite, les contributeurs peuvent proposer des `Diagnostics` (Quels problème, quels défis). Sur ces diagnostics, les utilisateurs peuvent indiqués s'ils `d'accord`, `mitigé`ou `pas d'accord`. Ce système permet de trier les diagnostics les plus partagés par la communautés.
Sur chaque diagnostics, les utilisateurs peuvent proposer des sources, des arguments `pour` et des arguments `contre`. Sur chacun des ces arguments, les utilisateurs peuvent voter `+1` : pour permettre de mettre en visibilité les meilleurs arguments.
Une consultation a une `durée` définie, à l'issue de la date de fin : `une synthèse` est construire à partir des diagnostics et des arguments les plus importants.

Exemple d'une consultation : https://contribuez.cnnumerique.fr/debat/economie-collaborative

Je pense que ce type de plateforme est inspirant et mériterait probablement une VE dédiée. Qu'en dites vous ?

**Comment by Frosty-Z** [comment]
+1 pour ajouter cela à ˋINSPIRATIONS.MDˋ. Je dirais que comme ça se rapproche beaucoup d'un système Q&A classique à quelques fonctions près, et que c'est un outil parmi d'autres (forum, t'chat etc.) sur la future plateforme LetsPlayScience, une VP devrait suffire, mais l'essentiel est que ce soit présent dans les "propositions concrètes" (VE ou VP)

**Comment by fsamin** [comment]
@Frosty-Z je t'invite prendre le temps de naviguer sur https://contribuez.cnnumerique.fr/consultations. Pour moi le plus intéressant c'est la démarche globale. De mon pointe de vue, elle colle plutôt bien aux attentes pour Lets-play-science et pourrait constituer une VE (ou alors je n'ai pas compris le sujet :smile: )
La plateforme est assez simple, mais c'est quand même assez différent d'un système de QA; avec la notion de diagnostics, d'argument pour/contre, les sources etc...

Le parti pris, à contre-courant- de n'apporter aucune fonctionnalité *sociale*, pour ne pas mettre en avant les contributeurs mais seulement le contenu est aussi intéressant et mérite d'être étudié.

**Comment by Frosty-Z** [comment]
[VE](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#II) : *ensemble de propositions qui offre une solution applicative cohérente*
En partant du principe que la "solution applicative" idéale comportera certainement plusieurs outils (par ex. forum + site web + écriture collaborative + ...), l'exemple **CNNumérique** ne correspondrait qu'à un seul de ces outils, et les fonctionnalités de base de cet outil sont vraiment celles d'un outil Q&A : un sujet, des propositions, des votes pour chaque proposition.

> Le parti pris, à contre-courant- de n'apporter aucune fonctionnalité sociale

* Jeff Atwood, co-fondateur de **StackOverflow**, a [également tout fait pour défavoriser la discussion sur SO](http://blog.codinghorror.com/civilized-discourse-construction-kit/).
* Des sites établis comme **Yahoo Q&A** et **Quora** mettent également très en retrait leurs fonctionnalité de commentaires sur les propositions. 

Donc bien que **CNNumérique** ne propose absolument aucune fonctionnalité de commentaire, ce n'est pas à proprement parler "à contre courant".

Seules différences notables que j'identifie :
* Les propositions ont 3 votes possibles (+1, -1, neutre) et c'est affiché sous forme de camembert dans la liste
* Pour chaque proposition, on peut ajouter des arguments pour/contre avec vote, *à la [Tricider](http://www.tricider.com)*
* Il n'y a aucune possibilité de tri sur les propositions ni sur les arguments, par nombre de votes (par ex. plus forte proportion de votes positifs décroissante), nombre de vues ou autre. Un peu moins pratique pour faire ressortir les propositions qui ont généré le plus d'activité / accords / désaccords, ça m'aurait semblé utile.
* La notion de source : toute relative, puisque sur n'importe quel site Q&A courant il suffit de copier-coller un lien pour faire office de source ; la présentation (+ interface pour uploader des fichiers je suppose) sur **CNNumérique** est simplement différente, mais sur le fond je ne vois aucun écart fondamental.

Avec tout mon respect pour ta contribution, je persiste à penser que pour ces quelques fonctionnalités spécifiques à un système "type questions/réponses", une VP serait la voie la plus adaptée. Mais bien entendu, tu es libre de proposer une VE en suivant si possible les ["guidelines"](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#1-critères-de-soumission-dune-ve).

**Comment by sveinburne** [comment]
Il semblerait qu'il y ait comme [**un écho**](http://arsindustrialis.org)

> Comme tout le monde, et comme ces illustres sœurs jumelles, nous aimons rire et vivre et chanter et danser - et nous tenons à continuer de pouvoir le faire.
>
Nous sommes des citoyens, au départ quatre philosophes et une juriste, très préoccupés par la situation de désarroi qui règne dans les pays du monde entier, et singulièrement les pays industriels, et plus encore dans notre pays, la France.
>
Nous sommes convaincus que cet état de fait n’est pas une fatalité, et nous voulons contribuer à en produire une intelligence collective, avec pour principale hypothèse de travail l’idée qu’un élément décisif du malaise contemporain – au sens où Freud parla en son temps d’un malaise dans la civilisation – tient à une mutation de ce que nous appelons les technologies de l’esprit, et, en référence à un texte de Michel Foucault (L’écriture de soi, paru dans …), les hypomnémata de notre temps.
>
En contribuant à l’émergence d’une intelligence collective, entre nous cinq, qui sommes à l’initiative de l’association ARS INDUSTRIALIS, mais aussi bien sûr entre nous et ceux que notre projet intéressera, et en recherchant les possibilités de débattre avec toutes les compétences possibles, toutes les disciplines, et toutes les dimensions de la société, et toutes les nationalités, dont celles d’Europe en particulier, nous souhaitons devenir une force de proposition, et non seulement de réflexion.
>
Nous sommes convaincus que la pensée aussi bien que la vie de l’esprit en général – la science, les arts, la musique, la littérature, la philosophie, et en fin de compte tout ce qui relève de ce que l’on appelle du mot très usé de « culture » - consiste d’abord à combattre. Combattre la bêtise, et d’abord sa propre bêtise, ou sa propre inculture. Combattre aussi les forces de régression qui encouragent la tendance bête inhérente à chacun d’entre nous.

**Comment by gossetj** [comment]
En effet, pour l'aspect philosophique et solutions sociales de la question, sa semble rejoindre le projet, je propose donc de l'ajouter à la partie théorie des inspirations, voire dans les solutions partielles maximum (je ne crois pas avoir vu de solution concrète)

**Comment by sveinburne** [comment]
@gossetj yes je vais m'en occuper dans la semaine! Je vais d'ailleurs faire du nettoyage ici pour qu'on s'y retrouve sur ce qui a été référencé dans INSPIRATION.MD! A mesure que le contenu est référencé, je pense supprimer les commentaires concernés, si vous n'y voyez pas d'inconvénients.

**Comment by sveinburne** [comment]
Encore des références !
- [Sydologie](http://sydologie.com/) Portail sur la pédagogie en ligne, plein de ressources innovantes y sont référencées
- [Pédagogie active](http://www.pedagogieactive.com/) Mouvement pour rénover l'enseignement, de bonnes idées à puiser je pense
- [Outil de génération de pages web interactives](https://www.genial.ly/) Je l'ai testé superficiellement mais ça m'avait l'air très prometteur ; découvert via **Sydologie**.

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#18
