### ISSUE TITLE
Membres observateurs

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#37]
A tous ceux qui ne sont pas issus du monde de l'informatique, mais qui souhaitent participer à la réflexion, signalez-vous ici!

**Comment by aurelBZH** [comment]
j'ai des base en developpement xeb et logiciel mais pas le temps de me plonger dans le developement de lets play science par contre je suis interessé par le projet

**Comment by sveinburne** [comment]
Salut @aurelBZH et bienvenue ! Quel est ton profil, tes domaines d'intérêt en dehors du web? IA et apprentissage automatique (j'ai cru voir ça sur ton github) ?

**Comment by aurelBZH** [comment]
Salut @sveinburne je suis étudiant en master bioinformatique je m'intéresse beaucoup a la modélisation et au traitement de données génomique

**Comment by sveinburne** [comment]
Parfait! Je t'ai ajouté dans [CONTRIBUTEURS.MD](https://github.com/sveinburne/lets-play-science/blob/master/CONTRIBUTEURS.MD)

**Comment by JulienPayot** [comment]
Bien le bonjour,

Je n'arrive pas a savoir s'il faut que je commente ici ou s'il faut que je fasse une nouvelle "issue".
A défaut je vais commenter.

J'aimerais participer à ce projet, je n'ai jamais eu l'occasion d'utiliser github mais j'aime découvrir et le projet est intéressant alors ça fait une bonne occasion de s'y mettre.
Si ça intéresse quelqu’un, je suis recetteur logiciel, et quand je m’ennui je fait des programmes à la con en C.
Je vais déjà farfouiller un peu tout le projet et je commencerais à contribuer quand j'aurais compris le but exact du projet et comment marche github.

Julien

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#16
