### ISSUE TITLE
Inspiration & Recherche

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#38]
**MÉTA-TOPIC :** Fil de discussion associé à [INSPIRATION.MD](https://github.com/sveinburne/lets-play-science/blob/master/THEORIE/INSPIRATION.MD). 

Ce fil de discussion permet de parler de l'organisation du document INSPIRATION.MD.
Pour discuter du contenu, rendez vous sur **l'issue #32**.

**Comment by Frosty-Z** [comment]
Pour info, je me suis permis de faire 2 micro retouches directement dans **master** sur `INSPIRATION.MD` (cf. [historique](https://github.com/sveinburne/lets-play-science/commits/master/INSPIRATION.MD))

**Comment by sveinburne** [comment]
Merci pour les coquilles !

**Comment by sveinburne** [comment]
[Pull request de @gossetj à évaluer](https://github.com/sveinburne/lets-play-science/pull/59) les gens, merci ! #59

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#15
