### ISSUE TITLE
Les Visions d'Ensemble (VE)

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#41]
**MÉTA-TOPIC :** Fil de discussion associé à [VISIONS.MD#I](https://github.com/sveinburne/lets-play-science/blob/master/PRATIQUE/VISIONS.MD#I). 

Ce fil de discussion permet de parler de la structuration des visions d'ensemble et de leur rôle. 

**Extrait** 
> *Une vision d'ensemble, VE, est un ensemble de propositions qui offre une solution applicative cohérente. [...] Elle doit s'appuyez rigoureusement sur le vocabulaire définit en #40*

**Comment by hantropi** [comment]
Je ne sais pas vraiment si c'est ici qu'on peut donner des idées (une petite partie d'une vision d'ensemble), mais j'en ai deux que je voudrais partager avec vous.

Premièrement, la gestion des messages par pertinence est, a mon sens, l'idée la plus importante de ce projet. Sauf que le problème, comme il a deja été fait remarquer, est que le système de Youtube est assez limitée : 2 boutons pour donner son avis sur un commentaire (avis qui n'a pas forcement de lien avec sa pertinence dans certains cas...) est assez léger. Pour remédier a ce problème, on peut ajouter *d'autres moyens* de mettre en avant ou pas un commentaire, comme sa **pertinence par rapport au sujet** ou bien son caractère a être complètement **hors de propos**. Ce decoupage permettrait principalement de mieux si retrouver notamment en "*rangeant*" les messages par catégorie (pertinent, hors de propos, etc.).

Deuxièmement, le **mind-mapping**. Ce concept est très *intéressant* mais aussi très *confus* : On a du mal a s'y retrouver avec chaque idées, sa part dans tous les sens (pour la representation que j'en ai vus, bien sur), etc. Je pense qu'il serait (sans rentrer dans les details techniques) plus intuitif ici de découper les *groupes* ou *divergences* d'idées de la meme manière que *Git* avec son **système de branche** : Une *branche* pour chaque *groupe*, qu'on peut materialiser par une couleur chacune autour ou a l'intérieur du cadre du post (pour les différenciés entre elles et la branche par défaut) et qu'il est possible de "rebrancher" (merge) sur une autre *branche* si les deux vont vers le meme *cheminement de pensées*.

**Comment by Frosty-Z** [comment]
@hantropi Salut et merci pour ta participation.

Pour ta "vision d'ensemble partielle" je crée [une nouvelle issue](https://github.com/sveinburne/lets-play-science/issues/49), puisque dans celle-ci on discute plutôt des "visions d'ensemble" en tant que telles (rôle, structure à respecter...), et non de leur contenu.

Pour le PS. je vois qu'un lien vers **Gitter** a été rajouté au début du `Readme.MD`

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#12
