### ISSUE TITLE
"décortiquer/découper la question"

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#44]
Copier-coller du post de @gossetj qui mérite un topic :

> Bonsoir tout le monde!
Désolé par avance si ce message est pas à la bonne place, je m'acclimate encore à Github.
>
> J'ai l'impression que à vouloir trouver une réponse, vous avez d'étudier plus précisemment la question de départ: comment faire colaborer 5000 cerveaux? (je vous en veux pas j'ai fait pareil ^^)
Le truc, c'est qu'il est important, à mon sens, de décortiquer la question afin de mettre en évidence plus facilement les facteurs affectant la solution à cette question et la façon qu'ils ont de le faire. En clair, je pense que le seul fait de proposer un découpage directement lié à la syntaxe de la question permettrait une lisibilité grandement améliorée (que ce soit pour le readme ou les prochains projets Let's Play Science.
> 
> On peut par exemple proposer une première branche sur la colaboration au sens large, et une autre sur l'humain au sens large.  A partir de là, une structure se dessinerais d'elle-même en séparant les concepts pour éviter les confusions -> d'où mon appui pour un système de mind mapping, avec un point de départ basé sur une découpe comme celle que j'ai proposé, visant non pas des réponses, mais des questions auxquelles on a trouvé des réponses afin de s'appuyer dessus.
Plus précisemment, le fait de séparer les concepts tant que possible sans totalement dénaturer le texte initial permet de procéder comme pour un développement web avec la structure avec par exemple HTML et la mise en page par CSS. Le simple fait de diviser le problème permet logiquement de faciliter le partage des tâches entre les 5000 cerveaux.
> 
> L'inconvénient évident de cette méthode est qu'elle ne permet pas, sans étape postérieure, de synthétiser les informations pour fournir un panel restreint de pistes.
> 
> On peut alors proposer une seconde étape consistant à synthétiser le tout étant tout de même correctement structuré grâce à l'étape précédente proposant un système de branches (fertiles ou stériles). Un code couleur peut d'ailleurs être trouvé pour améliorer la visibilité des idées neuves ou peu commentées, rejeter les branches stériles et mettre en avant les idées prédominantes pour la synthèse. 
> 
> Enfin, la synthèse n'est à mon sens pas une mise en appllication: j'entends par là que la synthèse mettra en évidence des pistes à fort potentiel, mais devrais être bien distinguée du développement d'un outil basé sur cette dernière.
> 
> En résumé de ce pavé César!!
quatre étapes clés: 
> - **la distinction des concepts piliers de la problématique**
> - **la recherche de problématiques liées ayant trouvé des réponses satisfaisantes ou pas, et évaluation de celles-ci (fertile/stérile/jeune pousse/spam)**
> - **la synthèse des informations évoquées**
> - **la mise en application des solutions trouvées**
> 
> ps: je viens d'avoir une idée pour imager mon propos: prenez une colonie de fourmis cherchant à apporter un panier rempli de raisins dégrappés. Une solution serait de faire porter le panier directement, mais il celà semble à priori dangereux pour ces pauvres créatures. Par contre, demander à chaque fourmi de porter un ou un groupe de raisin(s) et celles-ci en seront parfaitement capable et seront quasi aussi performante que si elles avaient porté le panier sans encombre. (A l'inverse, si on tente de décomposer le raisin en tout petits morceaux, tout l'intérêt par en poussière). Encore un point: une fourmi peut gérer plusieurs raisins, mais il est clair qu'il y a plus de probabilité qu'elle en fasse tomber que si elle se focalise sur un seul)
> On est certes plus intelligent que des fourmis, mais sa ne change pas le raisonnement, à un niveau simplement plus élevé de difficulté et d'intelligence
> 
> edit: même si une simple distinction des plateformes de réflexion collective et de vidéo est à mon avis suffisant à décourager les trolls et autres parasites, je pense qu'une modération faible suffira à éradiquer totalement le problème en bannissant par exemple les spameurs au delà d'un certain nombre de plaintes contre lui)
> 
> Merci à toi qui à réussi à arriver ici sans t'endormir :)

**Comment by sveinburne** [comment]
@gossetj, beaucoup d'éléments sur lesquels j'aimerais réagir. Mais avant toute chose, et juste pour être sur : tu parles de l'organisation actuelle de notre structure ([`label:méta-topic`](https://github.com/sveinburne/lets-play-science/issues?utf8=%E2%9C%93&q=label%3Am%C3%A9ta-topic)) ou bien tu essaies de te représenter la solution ([`label:vision d'ensemble`](https://github.com/sveinburne/lets-play-science/issues?q=label%3A%22vision+d%27ensemble%22))? `

**Comment by gossetj** [comment]
L'organisation actuelle  me pose problème mais je n'arrive pas ce n'est pas très grave puisque si elle l'était, on aurait plus à chercher une réponse à la question... J'imagine donc qu'on peut considérer mon post comme un essai de vision d'ensemble

**Comment by sveinburne** [comment]
Tu devras être plus clair à l'avenir selon que tu parles de la structure actuelle ou de la solution à notre problème, même si c'est difficile de ne pas mélanger les deux. 

La synthèse est là pour rapporter les idées de youtube de façon un peu "brut", sans trop les manipuler pour ne pas trop les dénaturer. Des documents de réflexion THE_APP.MD et INSPIRATION.MD associés au forum sont eux les supports de la réflexion. Mais tu peux tout à fait faire une proposition de restructuration *concrète* en #45, en nous expliquant les grands axes, avec quand même un bon niveau de détails, de la nouvelle mouture !

Nous avons déjà organisé un certain découpage, avec notamment les labels #39. La section *définitions* de THE_APP.MD nous permet d'organiser les concepts associés à l'application imaginée, tandis que le fichier INSPIRATION.MD permet d'aborder différents champs disciplinaires en relation avec la problématique. Pense-tu que notre structure ne fait pas un découpage suffisant, et si oui, que proposes-tu ? ( merci de créer un nouveau post là aussi, c'est encore une autre question! ) 

> quatre étapes clés:
*la distinction des concepts piliers de la problématique

Les concepts déjà présentés dans [THE_APP#I](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I) rejoignent pas mal ce que tu dis. 
*La distinction des concepts piliers de la problématique* s'opère dans l'optique **sémantique** de façon organique et émergente, confère toute la partie **sémantique** des définitions. 

> *la recherche de problématiques liées ayant trouvé des réponses satisfaisantes ou pas, et évaluation de celles-ci (fertile/stérile/jeune pousse/spam)

Concepts à concrétiser (fertile, stérile, jeune, pousse, spam) : qui étiquette ces idées, à quoi servent ces étiquettes ? J'ai l'impression que ça rejoint un petit peu l'idée de @Piratedu52, #27 (confère les **définitions chaînées**, **ontologie**, **web sémantique**). D'autres personnes avaient proposé de découper un **défi** en de multiple sous-défis, @Frosty-Z tu as une idée peut-être ?
En tout cas on est dans la question de l'émergence du savoir, c'est assez passionnant!

> la synthèse des informations évoquées
Voir la section de THE_APP#I sur le **versionnement**, qui fait de la synthèse un processus émergent, dynamique et **auto-régulé** ! Pas besoin d'avoir un groupe de personnes qui se décident à faire une synthèse pendant que d'autres continuent à fouiller, à moins que tu le voyais autrement ?

> la mise en application des solutions trouvées
Là j'ai l'impression que tu parles de nouveau de notre structure et pas de la problématique!

**Comment by gossetj** [comment]
D'accord, je crois que je commence à comprendre le système que vous avez mis en place avec les labels et tout. Je vous conseille par contre, pour les utilisateurs inexpérimentés comme moi, de décrire plus précisemment la manière de faire globale sur le readme histoire de faciliter la compréhension et vous éviter à toi et les autres modo d'avoir moins de boulot.

**Comment by sveinburne** [comment]
@gossetj on a justement fait cette refonte tout récemment ( confère #43 ), donc peut être tu es passé à côté du nouveau [README.MD](https://github.com/sveinburne/lets-play-science/blob/master/README.MD) ?

**Comment by gossetj** [comment]
Oui, je viens de le voir, juste après avoir posté ce dernier message :). C'est déjà bien plus clair!!

**Comment by sveinburne** [comment]
Ah bien j'suis heureux de voir que ça puisse servir ;) Peut-être on devrait donner un petit tutoriel sur l'utilisation du forum et de github en général ! Mais j'ai déjà pas mal donné ces derniers temps donc ça sera à d'autres personnes de s'emparer de l'initiative, faut que je bosse aussi lôle

**Comment by gossetj** [comment]
Je pensais justement aussi à un tuto, car le readme oriente plutôt bien, mais un tuto aurait l'avantage de pouvoir expliquer plus précisement la structure du projet (distinction des fichiers et des posts par exemple). Je ne voudrais pas raconter de conneries donc je propose qu'une personne plus proche du projet le fasse, comme @Frosty-Z par exemple ^^.

**Comment by sveinburne** [comment]
Ahah le pauvre on lui refile du boulot sur son dos! Mais oui ça m'a l'air nécessaire :+1:

**Comment by Frosty-Z** [comment]
Oh les petits malins qui me refilent le bébé... démerdez vous ! :-)

Sérieusement, pour ce dernier point je crois que ça peut être assez simple à améliorer. Je trouve également que le Readme est déjà bien structuré et clair désormais, il resterait peut être à renvoyer les nouveaux venus vers un "tuto github" (il doit en exister de très bien faits, je vais chercher) au niveau du point qui dit "si vous êtes un peu perdu...".
Je vais faire une petite PR à l'occasion, histoire que ce soit revu au moins par @sveinburne.

@gossetj merci pour tes interventions, j'essaierai d'y réagir dans le détail dès que je peux, j'espère demain soir.

**Comment by Frosty-Z** [comment]
A la relecture entière du topic, voici ce qui me vient à l'esprit en vrac :

* Question de @sveinburne concernant l'idée de **défi / sous-défi** : oui avec une plateforme Q&A bien pensée (cf. la VE que je vais bientôt "publier officiellement"), je pense qu'on peut aboutir à un système de structuration arborescente (ou mind mapping) qui peut évoluer presque de lui même, au fil de la participation des internautes. Au passage, je pense qu'il faut garder à l'esprit que la question porte *implicitement* sur la collaboration *en ligne* de 5000+ cerveaux *de manière asynchrone*.

Je remarque suite à l'intervention de @gossetj, que la "structuration de réponse" qu'on a défini comportait seulement *"réfléchir aux besoins ; rechercher et/ou développer des outils"*, mais qu'il y a un pan entier consistant à "approfondir la question" (études scientifiques liées sujet, domaines de recherche associés, etc.) qu'on a presque "oublié" dans cette structure.

Du coup l'"organisation mentale" de la réponse deviendrait plutôt :

*Comment faire collaborer 5000 cerveaux sur une question ?*
* **A l'aide d'outils de collaboration en ligne** (axe plus "outils concrets")
  * Réaliser une synthèse des commentaires
  * Chercher des outils
  * Rédiger des VE et en discuter
  * Développer une plateforme Open Source
     * Rédiger des specs
     * Lister les personnes intéressées et leurs compétences
     * Choisir des technos
     * etc.
* **Etudions de manière approfondie la question / le sujet** (axe plus "théorique")
  * Décortiquons la question
     * Notion de "collaboration"
     * Notion de "facteur humain"
     * ...
  * Domaines de recherche associés
  * Etudes scientifiques liées au sujet
  * Inspirations...

Peut-être que pour aller dans ce sens (si ça vous dit), l'introduction "objectifs" du `Readme` mériterait encore un petit ajustement :stuck_out_tongue_closed_eyes: 

----

* Concernant un **tuto Github** pour le `Readme`, j'ai cherché des tutos pour non développeurs... Bah je n'ai pas trouvé ce que je cherchais ! Je tombe toujours sur des trucs "orientés développeur". Sans forcément utiliser un client Git/Github et se griller des neurones avec des lignes de commandes, on peut contribuer (surtout sur du texte en Markdown !). Bon je vais voir ce que je peux faire comme tuto minimaliste à Github + ce projet, peut-être faire dans un `HELP.MD` à part, et on mettrait un lien depuis le `README.MD` et d'autres fichiers "collaboratifs" vers ce `HELP.MD`.

**Comment by sveinburne** [comment]
@Frosty-Z  +1000 ! 
La confusion entre l'organisation de notre travail et la réponse à la question en sera d'autant dissipée !

Pour le tuto, oui autant tout regrouper dans un fichier à part, on pourrait aussi faire des vidéos si on a la motiv'. Je ferais une section sur l'utilisation des filtres, sacrément pratique à mesure qu'il y a des posts en masse. En vrac : 
- Comment utiliser le forum
  - labels
  - filtres 
- Rejoindre le groupe Gitter
- Quand utiliser Gitter vs le Forum
- Comment faire une PR à la main
  - avec un fork 
  - en éditant directement le fichier qu'on veut modifier

**Comment by Frosty-Z** [comment]
@sveinburne Et voilà : [`HELP.MD`](https://github.com/sveinburne/lets-play-science/blob/master/HELP.MD).

Si ça te plaît on peut adapter `README` et `SYNTHESE` pour pointer vers `HELP` :wink:

**Comment by sveinburne** [comment]
Il me semble qu'on a bien digressé et que l'issue peut-être fermée!

**Comment by sveinburne** [comment]
@gossetj [les pistes](https://github.com/sveinburne/lets-play-science/blob/master/THEORIE/PISTES.MD) semblent bien répondre au besoin que tu avais formulé !
