### ISSUE TITLE
Badges et rôles

### ISSUE THREAD

**Issue by Gophys** [sveinburne/lets-play-science#48]
Le but de cette conversation est de parler des différentes possibilité d'organisation du **pouvoir** donne a certains membres de la foule. Je pense notamment au travail de **Modérateur**.

J'avais commence a en parler dans **#35**, voila mon approche:

Chaque individu a toujours le même pouvoir par rapport un au autre individu lors d'une prise de décision collective. Celle-ci peut être d'approuver une modification d'une idée, la prise de sanction envers un autre membre, ou toute autre forme de prise de décision que la foule pourrait être a traiter.

Certaines personnes peuvent se retrouver avec des status spéciaux permettant de mettre en avant des articles ou des comportements. Un peu comme des lanceurs d'alertes, le pouvoir de ces personnes ne servira pas a prendre la décision en elle même mais a sensibiliser les autres membres de la foule a des posts et des problèmes afin que ceux-ci ne soient pas noyés dans la masse d'information.

Je pensais notamment a trois rôles:

* **Policier**: personne mettant en avant les comportements non respectueux
* **Expert**: personne proposant de nouvelles solutions ou des modifications pertinentes dans un domaine particulier (physique, mathématique, biologie, économie, politique, musique etc...)
* **Journaliste**: personne donnant souvent un "pouce vert" aux nouvelles idées/modifications, avant d'être suivie par la foule

Le rôle s'obtient une fois qu'une personne a suffisamment effectue l'action correspondant au rôle correspondant, et que la **foule a approuve cette décision**. La foule ne vote pas pour attribue de rôle, mais celui-ci s'obtient  par le fait que la foule suit les mises en avant de cette personne. Le **rôle peut être perdu** si la foule ne suit plus ses mises en avant, ou bien si la personne ne fait plus son rôle. Enfin, rien n'empêcherai le **cumul des rôles**.

**Comment by sveinburne** [comment]
Hey! J'ai déjà repris une partie de la définition du **badge** dans THE_APP.MD

>
##### i. Rôle
Un *Rôle* est une mission assumée par un membre le temps d'un *défi*.
> Ex : Aggrégateur de [*références*](#I.1.d)
>
##### i. Badge
Distinction récompensant l'investissement et la bonne volonté d'un participant.
Exemples (proposés par [Gophys](https://github.com/Gophys)) :
* **Policier**: personne mettant en avant les comportements non respectueux
* **Expert**: personne proposant de nouvelles solutions ou des modifications pertinentes dans un domaine particulier
* **Journaliste**: personne donnant souvent un "pouce vert" aux nouvelles idées/modifications, avant d'être suivie par la foule

Autant que possible on va procéder avec des **définitions**. A chaque fois que quelqu'un propose quelque chose d'un peu plus précis, soit on amende une définition existante, soit on en crée une nouvelle! Quand ça sera stabilisé on pourra s'amuser à faire une mind-map si on veut^^ 

Comme tu peux le voir, la définition de **rôle** n'est pas vraiment la même que la tienne, mais il y a l'idée de l'aval de la **communauté** (que tu aimes appeler *foule*^^). 

> Certaines personnes peuvent se retrouver avec des status spéciaux permettant de mettre en avant des articles ou des comportements. Un peu comme des lanceurs d'alertes, le pouvoir de ces personnes ne servira pas a prendre la décision en elle même mais a sensibiliser les autres membres de la foule a des posts et des problèmes afin que ceux-ci ne soient pas noyés dans la masse d'information.

Quels sont les *pouvoirs* auxquels le membre discerné (qui a un badge) a droit? J'ai l'impression que tu fais allusion à un *pouvoir d'exposition* (la possibilité de mettre en avant des contenus). Mais pour le Policier et le Journaliste, comment se manifeste ce pouvoir ?

> Le rôle s'obtient une fois qu'une personne a suffisamment effectue l'action correspondant au rôle correspondant, et que la foule a approuve cette décision. La foule ne vote pas pour attribue de rôle, mais celui-ci s'obtient par le fait que la foule suit les mises en avant de cette personne. Le rôle peut être perdu si la foule ne suit plus ses mises en avant, ou bien si la personne ne fait plus son rôle.

Là tu introduis clairement un nouveau concept. Il y a donc une vision de la politique ou les **badges** sont gagnés à vie (ou au moins pour une durée fixe), et l'autre ou il sont suspendus à l'**approbation constante** de la foule, ils sont alors le fuit d'un processus totalement émergent. Je propose la définition suivante : 
> ##### j. Badge dynamique
*Badge* suspendu à l'approbation constante de la communauté. Ça veut dire qu'il peut être retiré n'importe quand si la communauté n'a pas apporté de soutien suffisant dans un laps de temps déterminé.

**Questions** : comment définir ces seuils? Comment juguler la variation de fréquentation pour ne pas avoir trop ou pas assez de journalistes par exemple? Ces paramètres sont-ils configurables par l'administrateur? (Je suis pour une approche 100% paramétrable perso)

**EDIT** : confère #50

**Comment by Frosty-Z** [comment]
Pour apporter un peu d'eau au moulin, sur SO je crois que la plupart des badges sont "décoratifs" par ex. est **"Sheriff"** quelqu'un qui a été modo (via élection) pendant 1 an.

Peu d'entre eux sont vraiment "utiles", la principale utilité je crois c'est pour accéder au statut de modérateur élu. On ne peut être candidat que si on a les badges **"Civic Duty"** (voter 300 fois ou +), **"Strunk & White"** (éditer 80 messages), **"Deputy"** (faire 80 signalements reconnus utiles) et **"Convention"** (avoir participé aux discussions sur SO depuis le site "méta").

A mon avis on n'a pas forcément besoin d'une mécanique aussi complexe dans un premier temps, mais c'est intéressant à étudier/réfléchir afin d'avoir un minimum d'auto régulation à terme, si la plateforme à venir devient suffisamment fréquentée (seuil de fréquentation à définir...).

**Comment by sveinburne** [comment]
@Frosty-Z Je suis de ton avis! Mais pour le moment je ne cherche pas à donner le mien, juste à faire émerger les concepts ; alors @Gophys n'hésite pas à rebondir.

**Comment by Gophys** [comment]
> Comme tu peux le voir, la définition de rôle n'est pas vraiment la même que la tienne, mais il y a l'idée de l'aval de la communauté (que tu aimes appeler foule^^). 

Je dis *foule* juste pour rester dans l'idée de *sagesse des foules*. J'aurais plus envie de dire **agora** mais bon c'est tu tatillonnage.

> Quels sont les pouvoirs auxquels le membre discerné (qui a un badge) a droit? J'ai l'impression que tu fais allusion à un pouvoir d'exposition (la possibilité de mettre en avant des contenus). Mais pour le Policier et le Journaliste, comment se manifeste ce pouvoir ?

Dans le cadre d'un site web (c'est surtout cette image que j'ai en tête mais ca peut facilement s'adapter a une autre forme je pense), il s'agirait de **page spéciales** dans lesquelles sont recensées les manifestations récentes des personnes possédant un badge. le mieux serait je pense de faire un exemple: un **Policier** se remarque un propos qu'il trouve antisémite dans un poste, il le signal comme tout un chacun le ferait en appuyant sur le bouton **signalement** présent  sur la page. Ce bouton est présent pour tout le monde, mais du fait de son statu de **policier**, le poste s'affichera en tête de liste sur un page **contenu soumis a modération**, afin d'être plus facilement visible pour être modéré facilement. Tout un chacun peut regarder ces avis et donner son opinion le fait de sanctionner ou non. Pour un **journaliste** c'est le fait de cliquer sur le bouton **bonne idée** qui permettrait de le mettre en une d'un page **bonnes trouvailles** pour le soumettre au vote. Le poste d'un **Expert** en informatique, mettrait directement ses postes se trouvant sous le *#informatique* dans la page **parole d'expert**. 

> Badge dynamique

Je préfère le statu de **dynamique** aux status de **permanant/temporaire**. Je pense qu'un mode politique dynamique permet de ne pas avoir a suivre quelqu'un ou bien attendre son approbation ou ses actions. Cela a pour avantage de ne pas a avoir a **attendre** que le modérateur rentre de vacances, ou de se retrouver sous la coupe d'un **adminidictateur**.

>  Questions : comment définir ces seuils? Comment juguler la variation de fréquentation pour ne pas avoir trop ou pas assez de journalistes par exemple? Ces paramètres sont-ils configurables par l'administrateur? (Je suis pour une approche 100% paramétrable perso)

Comme j'en ai déjà parle dans le #35 je suis pour un 100% paramétré par la foule. En évolution constante et dépendant de la volonté collective. Encore une fois, je suis contre l'idée d'un administrateur pour gérer une foule, une foule auto-régulée me semble être la meilleur solution (ou au moins une expérience intéressante a tenter.)

> A mon avis, on n'a pas forcément besoin d'une mécanique aussi complexe dans un premier temps, mais c'est intéressant à étudier/réfléchir afin d'avoir un minimum d'auto régulation à terme, si la plateforme à venir devient suffisamment fréquentée (seuil de fréquentation à définir...).

Mon idée serait de s'affranchir de ce système d'élection, la sélection des membres possédant des *avantages* se ferait de manière dynamique, continue, sans obligation ni contrainte. Mon système serait plus un système de cercle vertueux, plus on fait quelque chose de bien, plus ce qu'on fait de bien est visible pour le reste de la foule. Cela ne va pas dans le sens d'obtenir un badge qui brille sur sa page, mais d'une reconnaissance de la foule pour notre travail qui permet a la foule d'en tirer encore plus d'avantages.

**Comment by Frosty-Z** [comment]
> Encore une fois, je suis contre l'idée d'un administrateur pour gérer une foule, une foule auto-régulée me semble être la meilleur solution (ou au moins une expérience intéressante a tenter.)

Si j'ai bien suivi le reste de ton intervention, plus précisément tu es contre l'idée d'administrateurs **autoproclamés**, plutôt d'administrateur **plébiscités**.

Je te suis dans cette idée, que @sveinburne a rajouté dans les définitions (à ceci près que je pense que les définitions **Rôle** et **Badge** sont deux présentations d'un même concept), et qui rejoint aussi celle de [Modération méritocratique](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I.3.b), je crois que ça a été dit.

Restera à décider de la priorité à accorder à cette "feature" par rapport aux autres qui ne manqueront pas d'émerger. Il semble que la nécessité de disposer d'une plateforme de type "Meta StackOverflow" se fasse sentir... (VE la plus pertinente ? quels [votes par catégorie](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#g-vote-catégorique) permettre sur chaque post ? etc.)
Je remarque aussi que la feature de "vote sur les issues" est [très demandée](https://github.com/isaacs/github/issues/9) sur GitHub pour prioriser les bugs/features...

**Comment by Gophys** [comment]
> Si j'ai bien suivi le reste de ton intervention, plus précisément tu es contre l'idée d'administrateurs autoproclamés, plutôt d'administrateur plébiscités.

Je suis contre **l’idée d'administrateur** tout court. Toute décision devrait être soumise a referundum. Sans faire d'appel aux urnes, chacun donne son opinion sur une prise de décision. Avec pour seuil: si N personnes ont donne leur avis et que X% est pour alors la motion est adoptée, si Y% est contre alors la motion est rejetée, avec X+Y >= 100% et N, X et Y choisie (par moyenne des votes) par la foule.

**Comment by Frosty-Z** [comment]
Ok c'est plus clair. Je pense que cette vision mérite (justement) la rédaction d'une **vision d'ensemble** d'un système auto-régulé basé sur le référendum dès le départ (ce qui revient à dire que la plateforme souveraine, à la base, devrait permettre au moins ça + vraisemblablement un espace type forum de discussion), et sans administrateur autoproclamé ni plébiscité/élu (du moins, tant que la foule ne l'a pas souhaité par référendum ! :wink: ).

Il y aurait par ailleurs quelques concepts à approfondir d'emblée, sinon la plateforme ne serait pas utilisable : par exemple, si n'importe qui peut soumettre une question/décision à référendum, comment les autres individus choisiront parmi les décisions à prendre qui risquent d'être fort nombreuses ? la foule pourrait-elle par exemple mettre en avant (toujours par vote) les questions les plus pertinentes/importantes pour lesquels les seuils de participation/adoption/rejet n'ont pas encore été atteints ?...
Comment définir les valeurs de N, X et Y avant que la foule se soit approprié la plateforme collaborative (si ça marche) et décide des valeurs par "propositions moyennées" ?
etc...

**Comment by Gophys** [comment]
> Ok c'est plus clair. Je pense que cette vision mérite (justement) la rédaction d'une vision d'ensemble d'un système auto-régulé basé sur le référendum dès le départ (ce qui revient à dire que la plateforme souveraine, à la base, devrait permettre au moins ça + vraisemblablement un espace type forum de discussion), et sans administrateur autoproclamé ni plébiscité/élu (du moins, tant que la foule ne l'a pas souhaité par référendum ! :wink: ).

Ok je vais m'atteler a la rédaction de ma VE pour définir des bases claires auxquelles ont pourra faire référence ou qu'on pourra clarifier au fur et a mesure.

> Comment définir les valeurs de N, X et Y avant que la foule se soit approprié la plateforme collaborative (si ça marche) et décide des valeurs par "propositions moyennées" ?

Ne constituons pas nous même une foule ? Puisqu'a pirori nous serons les premiers utilisateur du projet que nous mettrons en place, nous serons les premiers a voter. 

> Il y aurait par ailleurs quelques aspects à approfondir d'emblée, sinon la plateforme ne serait pas utilisable : par exemple, si n'importe qui peut soumettre une question/décision à référendum, comment les autres individus choisiront parmi les décisions à prendre qui risquent d'être fort nombreuses ? la foule pourrait-elle par exemple mettre en avant (toujours par vote) les questions les plus pertinentes/importantes pour lesquels les seuils de participation/adoption/rejet n'ont pas encore été atteints ?...

D'où l'importance des rôles, pour mettre en avant certains sujets et ne pas les noyer dans la masse, les **experts** et les **journalistes** mettraient en évidence les sujets et propositions qui semblent important (tout est lie ^^)

Après je n'ai jamais suppose que la foule puisse prendre des décision d'ordre de changement du système. Ils ne proposeraient pas de pouvoir avoir le droit d'avoir un **administrateur** ou autre... Après rien n'empêche la foule de créer une nouvelle question sur la gestion de l'outil pour y trouver des améliorations etc... que nous autre développeurs nous ferions une joie de mettre en pratique. Après tout ce serait hypocrite de ma part de refuser d'écouter la foule alors que j'essaye de lui donner tous les pouvoirs.

**Comment by sveinburne** [comment]
@Gophys Juste une parenthèse sur l'optique de nos échanges, ça serait cool de me  faire un retour sur #54. Je m'intéresse aux concepts et définitions qui pourraient émerger de ta **VE**. Le **badge dynamique**, il me semble que tu étais d'accord pour qu'on l'adopte? 
Ta VE et cette discussion me font réaliser un certain nombre de choses.

Sur la question de l'**administration** à ne pas confondre avec **modération**. L'**administrateur** n'est autre que le type qui a la possibilité d'installer le site web et le paramétrer. 
Projetons-nous dans dans l'**application idéale**. De nombreuses fonctionnalités devraient y être paramétrables , comme par exemple les **catégories de vote catégorique**, les critères d'obtention des badges, le seuil de basculement d'un système à l'autre comme suggéré par @Frosty-Z ...etc. Cet ensemble de paramètres vu globalement peut laisser émerger une **tendance** dans la structure politique organisée autour d'un **défi**. Par exemple, une structure plutôt verticale ou plutôt horizontale, une **modération** plutôt **méritocratique**, **démocratique** ou **oligarchique**. Mais c'est aussi une **structure politique mobile**, qui peut évoluer lorsque certaines conditions sont vérifiées, ou comme tu le suggérais, lorsque la **communauté/foule** souhaite voter une évolution de structure. 

##### Je sais pas ce que vous en pensez, mais je trouve ça assez vertigineux de possibles! Ce serait un sorte de laboratoire politique permanent.

**Comment by sveinburne** [comment]
La VE étant rédigée, je me permets de fermer!
