### ISSUE TITLE
hantropi : ébauche de vision d'ensemble

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#49]
Reprise partielle d'un message de @hantropi afin d'en discuter dans un topic spécifique :

> Premièrement, la gestion des messages par pertinence est, a mon sens, l'idée la plus importante de ce projet. Sauf que le problème, comme il a deja été fait remarquer, est que le système de Youtube est assez limitée : 2 boutons pour donner son avis sur un commentaire (avis qui n'a pas forcement de lien avec sa pertinence dans certains cas...) est assez léger. Pour remédier a ce problème, on peut ajouter *d'autres moyens* de mettre en avant ou pas un commentaire, comme sa **pertinence par rapport au sujet** ou bien son caractère a être complètement **hors de propos**. Ce decoupage permettrait principalement de mieux si retrouver notamment en "*rangeant*" les messages par catégorie (pertinent, hors de propos, etc.).
> 
> Deuxièmement, le **mind-mapping**. Ce concept est très *intéressant* mais aussi très *confus* : On a du mal a s'y retrouver avec chaque idées, sa part dans tous les sens (pour la representation que j'en ai vus, bien sur), etc. Je pense qu'il serait (sans rentrer dans les details techniques) plus intuitif ici de découper les *groupes* ou *divergences* d'idées de la meme manière que *Git* avec son **système de branche** : Une *branche* pour chaque *groupe*, qu'on peut materialiser par une couleur chacune autour ou a l'intérieur du cadre du post (pour les différenciés entre elles et la branche par défaut) et qu'il est possible de "rebrancher" (merge) sur une autre *branche* si les deux vont vers le meme *cheminement de pensées*.

**Comment by Frosty-Z** [comment]
Pour ton 1er point, cela rejoint une proposition formulée très fréquemment, sous diverses appellations : "différents types de like", "[votes par catégorie](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I.3.g)"... cette dernière a été retenue dans le [fichier de définitions](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I.3.g).

Concernant le concept de **mind mapping** on est bien d'accord, c'est intéressant (voire un peu "à la mode" il semblerait), mais peut regrouper plein de manières différentes de le mettre en place (y compris une bête vue arborescente type système de fichiers)
Par contre à mon avis, l'utilité d'une **branche Git** (ou autre système de gestion de source) n'a pas grand chose à voir avec une **branche de réflexion** à un défi/question (= sous-défi, sous-question, sous-réflexion...), mais je pense comprendre ce que tu veux dire.
En tout cas c'est bien pour ça que dans la [synthèse des commentaires Youtube](https://github.com/sveinburne/lets-play-science/blob/master/SYNTHESE.MD#II), j'ai regroupé le concept de **structuration arborescente** (ce qui n'exclut pas pour gérer certains cas très particuliers de se retrouver avec des graphes, mais c'est presque un détail) et de **mind mapping** car il s'agit selon moi d'un seul et même concept.
Les bonnes questions ici, je crois, étant de savoir qui les met en place / modifie, comment, et (évidemment) le choix de la (des) représentation(s) visuelle(s)...

**Comment by Gophys** [comment]
Il me semble que @Piratdu52 et @sveinburne en parlent déjà pas mal la: #27

**Comment by sveinburne** [comment]
Les idées proposées ici sont déjà répertoriées dans les **définitions**, alors je me permets de fermer ! @hantropi, si tu estimes que les définitions ne reprennent pas exactement ta vision des choses, n'hésite pas à ouvrir une nouvelle issue pour faire un **amendement** voire une proposition de définition.
