### ISSUE TITLE
Compte-rendu?

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#50]
**EDIT** : [une restructuration va bientôt avoir lieu répondant à cette issue, cliquer ici pour en voir l'ébauche](https://app.classeur.io/#!/files/64ztFcBhtGAxGLRG0Zre).

La discussion en #48 me fait penser qu'il manque un niveau de détail entre **définition** et **vision d'ensemble** (THE_APP.MD). Peut-être des pages markdown séparées qui font le compte rendu des réflexions sur des points plus précis? Ces compte-rendu *ne doivent pas être partisans* mais permettent de s'attarder sur plus de détails sans trop encombrer la section **définitions**. 
L'autre approche est qu'on s'autorise à faire des définitions assez velues. Perso je préfère une approche concise, avec juste un lien vers le compte-rendu dans la définition.
Qu'en pensez-vous ? ( :+1:  ça me va pour une approbation, mais :-1: j'aimerais autant votre point de vue^^)

**Comment by Frosty-Z** [comment]
@sveinburne +1 pour garder des définitions concises.
Est-ce que l'idée proposée par @Gophys ne pourrait pas aller dans la partie "agrégation des propositions" du SYNTHESE.MD à tout hasard ? Il serait toujours possible de faire un lien depuis les définitions de THE_APP.MD vers la sous-rubrique correspondante de SYNTHESE.MD.

Je préférerais éviter de multiplier les fichiers si possible (bon sinon, au pire, on commencera à en regrouper certains dans des dossier distincts, comme les VE qui ont déjà le leur).

**Comment by Frosty-Z** [comment]
Et puis en même temps dans un autre topic je propose de créer un nouveau fichier HELP.MD donc bon... Si besoin de créer un nouveau fichier de "propositions de définitions" pas de souci.

**Comment by Gophys** [comment]
Il nous faudrait un site de sagesses des foules pour pouvoir nous y retrouver plus facilement  :stuck_out_tongue_winking_eye: Sans blaguer, je pense que l'on peut très vite voir les limites de Github pour résoudre... le problème qu'on veut résoudre.

Le fait est qu'il existe un wiki dans github que l'on devrait peut être utiliser pour régler ce problème. On pourrait y stocker les diverses définitions ainsi que les questions soulevées et les solutions proposées. On peut facilement y inclure des liens vers d'autres sections. On utilise les tickets pour discuter, les fichiers pour présenter des résumés du projet au propre et le wiki pour mettre plus de détails et des liens qui définitions plus précises.

**Comment by Frosty-Z** [comment]
Concernant l'utilisation du **Wiki GitHub**, je suis assez partagé mais plutôt favorable pour tenter l'expérience.

**Avantages** :
* On rédigerait l'essentiel de la documentation là où c'est "prévu" par GitHub ; l'arborescence de fichiers dans l'onglet **code** serait allégée de la doc
* Si on met le Wiki en "accès libre", les manips pour participer à l'écriture collaborative seraient **nettement moins complexes pour des non informaticiens**.

**Inconvénient** : 
* Soit on autorise n'importe qui à éditer, et ça peut vite devenir le boxon (pas de validation par PR, donc risques de réorganisations hasardeuses voire de vandalisme "à la Wikipedia"...). L'historique des modifs serait donc à surveiller comme du lait sur le feu.
* Soit on ne donne accès qu'aux "collaborateurs" (auto proclamés pour l'instant), donc exit l'aspect "sagesse des foules", à moins de faire ouvrir une issue par demande de modif, auquel cas on se retrouverait dans le même cas que les fichiers (en moins pratique que les PR où on peut discuter / corriger / commiter directement).
Par contre avec des PR sur fichiers, la modération peut évoluer facilement (par ex. validation selon nombre de *"Looks Good To Me"* suggérée par @fsamin), mais on ne peut pas décider de passer du jour au lendemain à "ouvert à tous" (et que du coup la modération se fasse plutôt "à posteriori").

A noter que : 
* Dans la liste des repos (relativement fréquentés) que GitHub met en avant pour la qualité de leurs Wikis, 3/9 sont *"ouverts à tous"* et 6/9 sont modifiables *seulement par les "collaborateurs"*.
* Les pages Wiki sont également hébergées sur serveur Git donc toutes les opérations permises par Git doivent l'être pour les pages Wiki (voir par ex. http://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki)

Vu la taille et la fréquentation actuelles de ce repo, je suis assez favorable pour migrer tout le texte sauf le `Readme` sur des pages Wiki (Markdown supporté donc ça devrait être simple), faire l'expérience de laisser "ouvert à tous" tant qu'on n'a pas de débordement ingérable, et en demandant d'ouvrir une **issue** avant de faire une modif "significative".
A tout moment, si nécessaire, on peut repasser sur un mode de type "groupe restreint de personnes autorisé à modifier", voire même "remigrer" assez facilement vers des fichiers MD si on fait bien attention à écrire toujours en Markdown.

Est-ce que c'est prioritaire ? Je dirais que si on décide de passer pour l'essentiel sur du Wiki, plus on le fait tôt moins ça fera de boulot... A voir ce qu'en pense @sveinburne.

**Comment by gossetj** [comment]
Concernant les deux possibilités de droit d'accés au wiki, si c'est possible, je serais pour un mode intermédiaire se basant sur la distinction du contenu et de la structure de chaque fichier. Pour le coup, la structure globale ne serait modifiable que par des membres modérateurs qui seraient sollicités par le biais d'issues, et le contenu serait plus libre à la modification.

**Comment by Frosty-Z** [comment]
@Gophys Le type d'accès au Wiki est modifiable globalement mais apparemment pas pour chaque fichier (cf https://help.github.com/articles/changing-access-permissions-for-wikis/)
Cependant ce que tu proposes est jouable si la structure de base est dans le Readme (qui servira toujours de page d'accueil de toute façon) et le reste dans le Wiki.

**Comment by Frosty-Z** [comment]
Bon en fait on est déjà complètement HS par rapport au sujet initial ; j'ai donc ouvert une nouvelle issue pour discuter de l'utilisation de l'espace Wiki GitHub ou non (#55).

**Comment by sveinburne** [comment]
**Problème adressé en #67**
