### ISSUE TITLE
Définitions chaînées

### ISSUE THREAD

**Issue by Piratdu52** [sveinburne/lets-play-science#51]
Ceci est la reprise de la discussion autour de ma proposition sur les Définitions chaînées qui a été définie autour de ma PR (pas le meilleur endroit pour discuter donc). Pour les curieux c'est par ici -> https://github.com/sveinburne/lets-play-science/pull/27 .

**Comment by sveinburne** [comment]
La définition actuelle des **Définitions Chaînées** n'est pas claire. Elle devrait s'appuyer plus explicitement sur le concept d'**ontologie**
> L'ontologie constitue en soi un modèle de données représentatif d'un ensemble de **concepts** dans un domaine, ainsi que des relations entre ces concepts (...) Plus simplement, on peut aussi dire que l' « ontologie est aux données ce que la grammaire est au langage ».  

*[Wikipedia](https://fr.wikipedia.org/wiki/Ontologie_%28informatique%29)*

Ces relations sont d'ailleurs appelées
- **relations sémantiques**
- **relations de subsomption**

Je propose d'expliciter le lien avec les **ontologies** : 
> ##### g. Définitions Chaînées
Un peu comme dans un wiki, des définitions sont référées les une aux autres par des *relations sémantiques* qualifiées.
Un peu comme dans un wiki, des définitions sont référées les une aux autres par des *relations sémantiques* d'une part, des [**relations de subsomption**](https://fr.wikipedia.org/wiki/Subsomption) d'autre part. L'ensemble de ces relations constitue une [**ontologie**](https://fr.wikipedia.org/wiki/Ontologie_%28informatique%29). 

**Reste un travail de recherche assez conséquent (et je ne doute pas, passionnant) sur les relations entre chaque définition. Je ne sais pas comment s'articulerait ta proposition de page-rank associé à une mind-map, mais elle découlera forcément de ces travaux de recherche**.

**Comment by Piratdu52** [comment]
Je suis dans une position difficile. J'aime beaucoup qu'on lie les idées que sont nés dans un coin de ma tête et qui on changé de forme avec le temps ( a savoir faire dessiner un monde à Wikipedia, en référence au Petit Prince, qui c'est transformé en une méthode de visualisation de lien sémantique entre concept) a des concept universitaire. 

D'un autre coté, j'ai l'impression qu'on noie le poisson. Ce qui me gêne le plus c'est ça "Un peu comme dans un wiki". Dans mon idée c'est plutôt "Au fur et a mesure que l'on génére un wiki, on en profite pour mettre des liens sémantique et de subsomption".

**Comment by sveinburne** [comment]
@Piratdu52, je serais heureux que tu nous donne ton avis sur la PR #73, qui propose notamment une redéfinition des **Définitions chaînées**. J'ai toujours en tête de demander à des gars de mon département spécialisés dans les ontologies, mais pas le temps ce mois ci, je ferais ça en janvier.
