### ISSUE TITLE
Fonctionnalite d'importation de commentaires youtubes (ou autres)

### ISSUE THREAD

**Issue by Phacocherman** [sveinburne/lets-play-science#53]
Dans le but de limiter les inconvenients d'une [application souveraine](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#a-application-souveraine), je pense qu'implementer un moyen d'importer les commentaires youtube peut etre interessant.
L'idee est de profiter de tous les avantages d'une application souveraine en tentant d'apporter un peu plus d'integration dans youtube.

Les avantages de l'importation sont surtout :
- eviter a l'utilisateur de reecrire la meme chose a deux endroits
- permettre a ceux qui n'utilisent pas la plateforme de quand meme voir au moins les premieres ebauches des posts
- dans le cas d'une utilisation de la syntaxe, augmenter la popularite de la plateforme pour les posts serieux
- permettre a leo de ne pas desactiver les commentaires sans avoir une separation des reponses en 2 communautes distinctes
- avoir un minimum d'integration dans youtube (ou autres d'ailleurs) sans les limitations techniques associees
Le tout reste une application souveraine, mais on essaie juste de limiter les inconvenients.

A priori on peut faire ca de plusieurs facons :
- A l'echelle de chaque utilisateur : chacun peut choisir quand il veut importer un commentaire en particulier.
- A une echelle plus globale : tous les commentaires comportant une certaine syntaxe seraient importes automatiquement a intervalles reguliers (sans reimporter ceux deja importes precedement ?)
- Il y en a d'autres bien sur ...

A noter que je ne parle pas de synchronisation complete des commentaires mais simplement d'une importation unique (repetable si besoin). Une synchronisation complete peut s'averer plus ou moins interessante selon les fonctionnalites qu'on souhaite implementer et selon ce qui est realisable ou non, mais je ne me suis pas penche sur la question pour l'instant.

**Comment by gossetj** [comment]
Si j'ai bien compris ta proposition, elle consisterait à mettre en place une sorte de passerelle entre les plateformes permettant de simplifier la participation des utilisateurs habitués à youtube en proposant un renvoi du commentaire directement vers la seconde plateforme. Si je ne me fourvoie pas, je ne suis alors pas d'accord avec toi, car je pense que l'intérêt de distinguer les deux plateformes est justement de distinguer sans difficulté les idées visant à répondre à la question des conversations ordinaires et autres commentaires.

**Comment by sveinburne** [comment]
**Reprise du commentaire Gitter**
Okaye, pour moi ça reste effectivement l'application souveraine dotée d'une fonctionnalité d'importation. Faudrait trouver le mot qui reprend ce concept pour le mettre dans les [**définitions**](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I). 
Sur le plan de mon opinion personnelle - qui n’interférera pas avec ton amendement ! #54 - j'ai peur que ça provoque plus de problèmes que ça n'apporte de solutions. Par contre, je ne serais pas contre l'idée de pouvoir effectuer des recherches dans les commentaires youtube depuis la plateforme, comme sorte de matière première à la réflexion. En fait, c'est surtout la vision asynchrone qui me rebute... Dans la chronologie d'un défi, le t_0 c'est le moment ou Léo poste sa vidéo. Donc quand devrions nous procéder à l'importation? Devrions-nous le faire à plusieurs reprises? Si oui, pourquoi ne pas la rendre synchrone? Si oui, on risque d'avoir un paquêt de contraintes techniques rendant difficile l'implémentation des aspects sémantiques comme tu le soulignais. Bref, gros Oroborus. De mon point de vue, l'idée d'intégrer en partie les commentaires dans la plateforme est bonne, mais avec un cloisonnement strict entre les deux sources de données. Dans tous les cas, on va restructurer un petit peu la section THE_APP.MD#I.6

**Comment by Gophys** [comment]
Outre l'aspect technique de l'importation, qu'en est-il de l'aspect légal? Peut-on importer des commentaires YouTube en toute légalité? Quelles sont les contraintes imposées par la plateforme? Quid de la modération des commentaire?

**Comment by sveinburne** [comment]
:+1: @Gophys, un volontaire pour aller creuser la question ?

**Comment by Phacocherman** [comment]
@Gophys Je suis loin d'etre expert en droits mais d'apres quelques articles des conditions d'utilisation dont celui-ci (4.A) :
"You agree not to distribute in any medium any part of the Service or the Content without YouTube's prior written authorization, unless YouTube makes available the means for such distribution through functionality offered by the Service (such as the Embeddable Player)."

Une fonctionnalite d'importation des commentaires (qui sont consideres comme du Content) ne serait pas autorisee a moins d'obtenir une autorisation speciale de Youtube. De meme pour une application integree, je pense.

Notes :
- je crois que les commentaires sont consideres comme du Content a cause de l'article 6.A
"As a YouTube account holder you may submit Content to the Service, including videos and user comments. You understand that YouTube does not guarantee any confidentiality with respect to any Content you submit."

- Mais peut-etre que c'est quand meme legal (sans autorisation) si chacun n'est capable d'importer que ses propres commentaires (et qu'il y a confirmation de l'identite par connexion a google+) (6.C)
"For clarity, you retain all of your ownership rights in your Content. However, by submitting Content to YouTube, you hereby grant YouTube a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the Content in connection with the Service and YouTube's (and its successors' and affiliates') business, including without limitation for promoting and redistributing part or all of the Service (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each user of the Service a non-exclusive license to access your Content through the Service, and to use, reproduce, distribute, display and perform such Content as permitted through the functionality of the Service and under these Terms of Service. [...]"

Enfin, encore une fois je suis loin d'etre capable de dire si oui ou non c'est legal. L'ideal serait de contacter Youtube si on decide d'implementer cette fonctionnalite ou une autre similaire (ou pour une application integree aussi).

**Comment by Phacocherman** [comment]
@gossetj Je suis d'accord sur le fait que la situation ideale laisserait les commentaires banals sur youtube et les solutions collaboratives serieuses sur la plateforme. Toutefois, le but est ici de permettre aux utilisateurs (habitues a youtube) de faire evoluer leur simple commentaire en une nouvelle idee collaborative (i.e un post) s'ils en ont envie par la suite (par exemple, si l'utilisateur recoit des retours qu'il aimerait integrer et developper d'avantage). Aussi, il faut considerer que beaucoup n'utiliseront pas la plateforme, surtout au debut, que ce soit par habitude, par oubli ou meme par "flemme d'utiliser un nouvel outil". Leur permetttre une transition simple, sans avoir a reecrire leurs idees peut eventuellement s'averer utile, et cela permettrait a terme de s'assurer que toutes les solutions/idees interessantes sont presentes sur la plateforme. Enfin, garder les 2 plateformes completement distinctes risque de "former" 2 communautes distinctes aux reponses et idees distinctes, ce qui semble etre l'oppose de notre but (vu qu'on cherche a faire collaborer 5000 cerveau et non pas 2 x 2500).

**Comment by sveinburne** [comment]
@Phacocherman J'ai un peu revue ma copie^^ J'insiste sur le fait que ce sont des opinions **partisanes** (cf #54), et que quoi qu'il en soit ta proposition sera retenue. 

> Leur permettre une transition simple ... 

Je trouve que c'est un vrai plus de faciliter la transition, mais : 
- N'oublions pas que dans ce scénario, Léo donnerait un lien à la fin de sa vidéo pour demander aux utilisateurs de participer. Son pouvoir d'influence serait assez colossal. 
- Notre solution est une réponse générique à une question générique, et ne devrait pas être *trop* contextualisée à LetsPlayScience, même si c'est naturel et tentant. 
- Cependant d'autres youtubeurs pourraient être intéressés, et cette fonctionnalité gagnerait en généricité. 

> A l'echelle de chaque utilisateur : chacun peut choisir quand il veut importer un commentaire en particulier.

Je suis partagé :
- c'est une fonctionnalité bien pratique 
- mais en laissant la possibilité d'importer ses commentaires depuis youtube, on admet qu'il y a deux espaces viables pour collaborer ! C'est comme si on créait de manière [**performative**](https://fr.wikipedia.org/wiki/Performativit%C3%A9), les vases-clos dont on craint justement l'émergence... 

>A une échelle plus globale : tous les commentaires comportant une certaine syntaxe seraient importes automatiquement a intervalles reguliers (sans reimporter ceux deja importes precedement ?)

Voici mes réserves à des **snapshots/instantanés** réguliers : 
- ça risque de pousser les gens à **rester sur youtube**, on leur tend la pilule de la fainéantise ! 
- ça ne résout pas en entier le problème des vases clos, à moins que les posts de l'application souveraine soient dupliqués sur YT
- ça risque de poser pas mal de problèmes techniques, et notamment : comment distinguer les **posts** des **commentaires**. 


En admettant que le but est de **faciliter l'entrée des participants sur l'application souveraine**, voici une alternative moins complexe : *Cloisonner* les commentaires youtube de l'**application souveraine** tout en permettant  
- d'effectuer des recherches dans ces commentaires youtube 
- à titre individuel et à partir d'une authentification par google, de **transférer** un commentaire dans la plateforme (ton premier point) 

Je suis cependant partagé au sujet de ma proposition pour les même raisons que précédemment, notamment l'acte performatif. 

@gossetj j'aime beaucoup le mot **passerelle**, je vote pour qu'on le garde!

**Comment by fsamin** [comment]
Pour compléter avec les ToS de Youtube.
```
YouTube accorde [...] l'autorisation d'utiliser des spiders pour copier des données à partir du site dans le seul but de créer des index de ces données consultables par le public, mais non des caches ou des archives de ces données. [...]
```

Importer est donc possible mais seulement s'il a des fins d'indexation ou de référencement. 
Faire une application souveraine capable de faire référencer ou faire une __passerelle__ vers du contenu Youtube est donc possible - à des fins non commerciales (c'est un autre point des ToS de YT-Data-API).

**Comment by sveinburne** [comment]
Voici ce que je suggère pour cette proposition : on attends que la restructuration ait eu lieu ( #67 ) et on propose une **Vision partielle** qui fait la synthèse de tout ce qui a été dit. Puis on définit **passerelle** dans le nouveau DEFINITIONS.MD.

**Comment by sveinburne** [comment]
@Phacocherman chaud pour rédiger une synthèse de cette discussion qu'on la mette dans une vision partielle? Si jamais tu n'es pas familier de github, tu peux générer ta synthèse sur [cet editeur markdown en ligne](http://dillinger.io/) et nous envoyer le lien!

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#9
