### ISSUE TITLE
Proposition, Connaissance / Partisane, Impartiale

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#54]
Jusqu'ici, j'ai l'impression que les définitions nous ont quand même bien aidé. Voici une offre de définitions pour remédier clairement à l'ambiguïté de nos réactions face à une proposition. Nous devons avoir à l'esprit que nous cherchons l'**impartialité** face à une proposition nouvelle, et que viendra plus tard un temps pour les opinions **partisanes**. C'est la raison pour laquelle on a créé une section [**définitions**](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I).
**Ces définitions vous semblent-elles pertinentes? Si non, pourquoi, quels amendements proposeriez-vous?**

> #### Connaissance
Dans le cadre d'un défi, élément de réponse **servant la compréhension**, que souhaite partager un *membre* avec la *communauté*.
**Ex** :  une synthèse sur les ontologies
> #### Proposition
Dans le cadre d'un *défi*, élément de réponse **servant un but** inféré - déduit - de la problématique, que souhaite partager un *membre* avec la *communauté*.  
**Ex** : une fonctionnalité de l'application 
>
> #### Partisane
Dans le cadre d'un *défi*, se dit d'une opinion qui penche de façon totalement **assumée** en faveur des avantages ou des inconvénients d'une *proposition*.  
>
> #### Impartiale
Dans le cadre d'un *défi*, se dit d'une opinion qui **cherche** délibérément la neutralité en se concentrant sur la **compréhension** de la *proposition* de son/ses interlocuteurs, et non leur réfutation. Une posture impartiale nous permet d'évaluer les avantages et inconvénients en laissant de côté notre égo.

**Comment by Frosty-Z** [comment]
Tout ça me va très bien :+1: 

C'est vrai que j'ai souvent tendance à donner mon avis sur des *propositions* alors qu'on est loin d'être au state de discuter de la priorité d'éventuelles fonctionnalités qui en découleraient. Je vais attendre un peu pour m'enflammer alors :wink:

**Comment by sveinburne** [comment]
@Frosty-Z  Et moi de même! J'ai réalisé qu'en posant clairement un temps pour imaginer et un temps pour décider, on se donnait beaucoup plus de libertés et on s'empêchait de se disputer pour des broutilles. D'autant que nos avis respectifs auront beaucoup plus de pertinence lorsqu'on aura chacun creusé le sujet en profondeur.

**Comment by fsamin** [comment]
Je suis en phase avec __Connaissance__ et __Proposition__
J'ai plus de mal à situer __Partisane__ et __Impartiale__ qui sont des adjectifs qui définissent une *opinion* (dixit) la définition...

Je comprends où tu veux venir, mais il me manque un bout de ta reflexion pour situer ces deux derniers points. En fait j'ai l'impression qu'on veut dire deux fois la même chose : une connaissance __DOIT__ être impartiale, et une proposition __EST__ (par nature) partisane.

Peux-tu m'éclairer ?

**Comment by fsamin** [comment]
En complément, pour caractériser les réactions face à une intervention, une bonne grille de lecture est les attitudes de Porter : http://www.fr.wikimediation.org/index.php?title=Les_six_attitudes_de_Porter

**Comment by sveinburne** [comment]
@fsamin 
>En complément, pour caractériser les réactions face à une intervention, une bonne grille de lecture est les attitudes de Porter : http://www.fr.wikimediation.org/index.php?title=Les_six_attitudes_de_Porter

Merci beaucoup pour ce lien, très intéressant! Il mériterait d'être mit dans INSPIRATION.MD (qui sert d'index en fait) 

>Je comprends où tu veux venir, mais il me manque un bout de ta réflexion pour situer ces deux derniers points. En fait j'ai l'impression qu'on veut dire deux fois la même chose : une connaissance DOIT être impartiale, et une proposition EST (par nature) partisane.

Si ça n'est pas clair alors il faudra que je revois un peu cette proposition! S'il y a des amoureux des lettres qui me proposent des concepts plus clairs, j'amende volontiers la définition. Sinon on va le faire nous même. Il faut distinguer l'objet *la proposition, la connaissance* du sujet, la subjectivité, le locuteur. Le locuteur peut avoir une posture *partisane* ou *impartiale*. Mais **il ne peut pas** être objectivement impartial. 
Avoir une posture *partisane* signifie qu'on assume devant son interlocuteur que nous exprimons un avis. Avoir une posture *impartiale* signifie qu'on assume devant son interlocuteur qu'on cherche l'objectivité. 

L'intérêt de ces définitions est de rappeler à chaque membre de la communauté **l'inter-subjectivité** d'une collaboration en ligne. 

Mais peut-être y-a-t-il une meilleure manière d'exprimer ça à partir des attitudes de Porter qui abordent tout à fait ce problème, que proposerais-tu ?

**Comment by fsamin** [comment]
Ok, merci donc j'avais bien compris où tu voulais en venir :-)
En fait on est sur des notions complètement différentes entre "Connaissance" et "Proposition" d'une part; et "posture impartiale", "posture partisane" d'autre part.

Je plussoie le fait de définir et de caractériser les interventions par "connaissance" et "proposition". Il y a probablement d'autre type par exemple "reformulation", "interrogation", ... 
Par contre je ne vois pas vraiment la plue-value de définir et caractériser les postures.

**Comment by sveinburne** [comment]
**Consensus tacite adopté pour Proposition et Connaissance**. 
@fsamin Pour les deux autres définitions, elles sont là pour rappeler à la communauté qu'on devrait réfléchir à notre posture lorsqu'on s'adresse à quelqu'un. Mais je pense que ça peut faire l'objet d'une réflexion assez complète, voire d'un **piste** (cf #67). Donc je le laisse de côté pour le moment et ferme cette issue! On va avoir l'occasion d'en rediscuter.
