### ISSUE TITLE
Utiliser le Wiki GitHub ?

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#55]
Nouvelle discussion extraite de la #50 

Lancée par @Gophys :
> Le fait est qu'il existe un wiki dans github que l'on devrait peut être utiliser pour régler ce problème. On pourrait y stocker les diverses définitions ainsi que les questions soulevées et les solutions proposées. On peut facilement y inclure des liens vers d'autres sections. On utilise les tickets pour discuter, les fichiers pour présenter des résumés du projet au propre et le wiki pour mettre plus de détails et des liens qui définitions plus précises. 

Réponse de @Frosty-Z
> Concernant l'utilisation du **Wiki GitHub**, je suis assez partagé mais plutôt favorable pour tenter l'expérience.
> 
> **Avantages** :
> * On rédigerait l'essentiel de la documentation là où c'est "prévu" par GitHub ; l'arborescence de fichiers dans l'onglet **code** serait allégée de la doc
> * Si on met le Wiki en "accès libre", les manips pour participer à l'écriture collaborative seraient **nettement moins complexes pour des non informaticiens**.
> 
> **Inconvénient** : 
> * Soit on autorise n'importe qui à éditer, et ça peut vite devenir le boxon (pas de validation par PR, donc risques de réorganisations hasardeuses voire de vandalisme "à la Wikipedia"...). L'historique des modifs serait donc à surveiller comme du lait sur le feu.
> * Soit on ne donne accès qu'aux "collaborateurs" (auto proclamés pour l'instant), donc exit l'aspect "sagesse des foules", à moins de faire ouvrir une issue par demande de modif, auquel cas on se retrouverait dans le même cas que les fichiers (en moins pratique que les PR où on peut discuter / corriger / commiter directement).
> Par contre avec des PR sur fichiers, la modération peut évoluer facilement (par ex. validation selon nombre de *"Looks Good To Me"* suggérée par @fsamin), mais on ne peut pas passer à un mode "ouvert à tous" (et que du coup la modération se fasse plutôt "à posteriori").
> 
> A noter que : 
> * Dans la liste des repos (relativement fréquentés) que GitHub met en avant pour la qualité de leurs Wikis, 3/9 sont *"ouverts à tous"* et 6/9 sont modifiables *seulement par les "collaborateurs"*.
> * Les pages Wiki sont également hébergées sur serveur Git donc toutes les opérations permises par Git doivent l'être pour les pages Wiki (voir par ex. http://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki)
> 
> Vu la taille et la fréquentation actuelles de ce repo, je suis assez favorable pour migrer tout le texte sauf le `Readme` sur des pages Wiki (Markdown supporté donc ça devrait être simple), faire l'expérience de laisser "ouvert à tous" tant qu'on n'a pas de débordement ingérable, et en demandant d'ouvrir une **issue** avant de faire une modif "significative".
> A tout moment, si nécessaire, on peut repasser sur un mode de type "groupe restreint de personnes autorisé à modifier", voire même "remigrer" assez facilement vers des fichiers MD si on fait bien attention à écrire toujours en Markdown.
>
> Est-ce que c'est prioritaire ? Je dirais que si on décide de passer pour l'essentiel sur du Wiki, plus on le fait tôt moins ça fera de boulot...
>
> @sveinburne qu'en penses tu ?

@gossetj : 

> Concernant les deux possibilités de droit d'accés au wiki, si c'est possible, je serais pour un mode intermédiaire se basant sur la distinction du contenu et de la structure de chaque fichier. Pour le coup, la structure globale ne serait modifiable que par des membres modérateurs qui seraient sollicités par le biais d'issues, et le contenu serait plus libre à la modification.

@Frosty-Z :

> @gossetj Le type d'accès au Wiki est modifiable globalement mais apparemment pas pour chaque fichier (cf https://help.github.com/articles/changing-access-permissions-for-wikis/)
Cependant ce que tu proposes est jouable si la structure de base est dans le Readme (qui servira toujours de page d'accueil de toute façon) et le reste dans le Wiki.

@sveinburne (copié du t'chat)

> @Gophys Utiliser le wiki intégré de github est une option pour organiser un peu mieux la navigation, je rejoins les arguments de @Frosty-Z en partie... je suis par contre pour une modération des contenus. Pourquoi? Parce que les participants doivent d'abord connaitre la structure et la logique du wiki avant de pouvoir l'éditer... Il est par exemple tentant pour un participant de s'exprimer sur l'utilité d'une fonctionnalité décrite dans une définition en expliquant pourquoi la sienne est meilleure, alors que la section définitions ne doit pas être partisane et ne participe pas d'une seule solution. Du coup, je suis hésitant...
> Autre question sur les Wiki Github : est-ce qu'il supporte une structure arborescente ? J'en ai pas l'impression...
> Ah si https://help.github.com/assets/images/help/wiki/wiki_main_showcase.png

@Frosty-Z (copié du t'chat)

> @sveinburne dans l'hypothèse du "wiki ouvert à tous" l'idée serait une modération à posteriori, si qqn fait un ajout au mauvais endroit, on le déplace, s'il ajoute n'importe quoi, on le vire. Au moins tant que la fréquentation est relativement faible je serais partant pour expérimenter ça (car beaucoup plus facile de participer pour un non informaticien).

**Comment by sveinburne** [comment]
Après un temps de réflexion, je maintiens ma réticence à ouvrir le wiki, même s'il y a des avantages évidents. Voici les points qui me font basculer contre : 
- Parmi les objectifs du projet, le brassage des idées est un élément clé de sa réussite. 
- Or la possibilité d'éditer le wiki, les définitions etc... à tout va, sans passer par une *issue* ou une *PR* fait que **les idées vont des auteurs aux documents, sans passer nécessairement par la communauté**. C'est l**écueil du nombrilisme**.

Il me semble évident que **nous devrions faciliter encore la manière de participer pour les non informaticiens**. Plusieurs idées : 
- Formaliser un peu mieux la manière de participer **sans PR** c-à-d via issues, suivant qu'on offre une VE, une définition etc... je vais essayer de clarifier ça à mesure que la nouvelle restructuration prend forme. 
- Orienter les participants vers des outils pour éditer en Markdown plus facilement, + mini tuto. 
  - [Atom](https://atom.io/) + [Markdown preview plus](https://atom.io/packages/markdown-preview-plus)
  - [stackedit.io](https://stackedit.io/editor) ( ça m'a l'air d'être la meilleure solution comme **alternative aux PR** )

**Mais je ne souhaite pas décider seul**.

**Comment by Frosty-Z** [comment]
@sveinburne 

Tes craintes sont fondées, comme je disais, je ne tenterais pas l'expérience du Wiki "ouvert" sans demander dans le `Readme` que toute modif significative (genre > 3 lignes ajoutées/modifiées) soit discutée au préalable dans une issue.

En même temps, ça ne ferait pas un changement radical par rapport au système actuel.

J'aime beaucoup l'aspect "accessibilité" du Wiki, mais la modération/revue étant clairement plus délicate, je vais rester neutre.

Je crois qu'il nous faudrait quelques avis supplémentaires, en attendant on peut mettre en avant les 2 pistes que tu as proposées à la fin de ton dernier message au niveau `Readme`/tuto.

**Comment by sveinburne** [comment]
Ça me va, j'attends d'autres arguments / avis !

**Comment by fsamin** [comment]
@sveinburne, @Frosty-Z  +1 avec ce vos avis sur le wiki

Une proposition de contribution peut se faire plus facilement et de manière plus structurée via une __issue__. 

Dans un second temps, on peut facilement imaginer que suite au triage et la validation d'une __issue__ celle-ci fera l'objet d'une __PR__ pour rejoindre le master. En référençant/taggant bien les issues comme vous avez commencé à le faire : la communauté devrait s'y retrouver.

**Comment by sveinburne** [comment]
Comme l'a suggéré @Frosty-Z, on va attendre **Mardi 8** avant de valider [le consensus](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I.3.k). Ensuite, **restructuration** du *repo* en accord avec #60, [voici une ébauche](https://app.classeur.io/#!/files/64ztFcBhtGAxGLRG0Zre) qui sera ensuite soumise au processus de décision par consensus tacite.

**Comment by sveinburne** [comment]
@fsamin C'est aussi ma vision :). On va devoir mettre à jour la documentation pour mieux guider la communauté sur la participation, c'est encore un peu flou. Ça sera le prochain chantier après la restructuration !

**Comment by Frosty-Z** [comment]
> Comme l'a suggéré @Frosty-Z, on va attendre **Mardi 8** avant de valider le consensus **à moins que suffisamment de personnes s'expriment contre un portage sur wiki**.

Tu voulais dire "s'expriment ***pour*** un portage" ?

Sauf autres avis argumentés en faveur du wiki d'ici mardi, vu le consensus qui se dégage actuellement de la discussion, ma compréhension est qu'on poursuit avec les `.MD`...

**Comment by sveinburne** [comment]
**Consensus tacite atteint (+72h)**, je ferme! Si quelqu'un s'y oppose, je peux bien entendu rouvrir.
