### ISSUE TITLE
Lien sémantique

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#57]
Il me semble nécessaire d'approfondir le concept de **lien sémantique** pour ne pas le confondre avec celui de **relation sémantique** propre à une [**ontologie**](https://fr.wikipedia.org/wiki/Ontologie_%28informatique%29), cf #51

La définition actuelle de carte heuristique :
> ##### a. Carte Heuristique / Mind map
Vue en 2D sous forme de diagramme de graphe ordonné des liens sémantiques *entre posts*

La définition se réfère à des **liens sémantiques** sans en préciser la nature. Ils demandent à être explicités, 
~~voici une proposition :~~

> ~~**lien sémantique fort** : Un **chemin** complet du graphe, soit un **hash sémantique** complet~~ 
> ~~**lien sémantique faible** : Un **sommet** du graphe partagé entre deux posts~~

Voici la deuxième révision que je propose  :

> ~~lien sémantique~~ remplacé par **appariement** : Dans une *taxonomie*, proximité entre deux items. 
> **appariement fort** : Un **chemin** complet du graphe, soit un **hash sémantique** complet est partagé entre deux items. Ex : `#alimentation:breuvages:thé` partagé entre deux *posts*.
> **appariement faible** : Un **sommet** du graphe est partagé entre deux items. Ex : `#comestible:breuvages:thé` pour *post 1* et `#Angleterre:colonisation:Inde:thé` pour *post 2*. 

*relation sémantique* est inchangée.

**Comment by Frosty-Z** [comment]
Pour moi la définition actuelle est déjà suffisante.

J'ai du mal à voir la distinction qui pourrait exister entre "lien sémantique" et "relation sémantique", un exemple peut-être ?

Pour info, les auteurs de [l'article Wikipedia sur l'ontologie informatique](https://fr.wikipedia.org/wiki/Ontologie_(informatique)) ont l'air de considérer que c'est la même chose...
> relations : les liens que les objets peuvent avoir entre eux ;

**Comment by sveinburne** [comment]
Effectivement, la différence est arbitraire, et on pourrait choisir d'autres mots pour la désigner. Dans le cadre de **définitions chaînées**, une *relation sémantique* est **caractérisée**. C'est à dire que l'hyperlien (la référence à une définition dans une autre) est qualifié (il exprime une Spécialisation, Association... ). @Piratdu52 parlait de **balises sémantiques** (#27). C'est un concept qu'il m'a semblé très proche des **relations sémantiques** telles que définies dans une ontologie. 

Les **liens sémantiques** dans notre vocabulaire expriment un simple appariement (matching) de mots-clés (hash) associés à des posts, cf la définition ci-dessus. Ce sont donc deux choses bien distinctes. Mais faudrait ptetre justement les appeler **appariement sémantique** pour expliciter la différence.

**Comment by Frosty-Z** [comment]
Donc on aurait deux termes très proches ("lien" et "relation") pour des définitions assez distinctes, ça peut jouer des tours...

A mon avis :
* Dans la section **4. sémantique** de `THE_APP`, on peut rajouter des définitions pour **lien/relation sémantique** (au sens large) et **lien/relation sémantique qualifié/caractérisé** (pouvant être compris au sens d'une ontologie informatique)
* De même dans les discussions, on apporte un minimum de précision sur la notion de **lien** ou **relation sémantique** de laquelle on souhaite parler (lien/relation sémantique, caractérisé ou non, pour des mots clés, tags, idées, concepts, sous-défis...)

**Comment by fsamin** [comment]
Si j'ai bien compris ce que tu dis @sveinburne, tu différencies :
 - __Relation sémantique__ : qui relève de l'ontologie ?
 - __Lien sémantique__ : qui relève de la taxonomie ?

**Comment by sveinburne** [comment]
@fsamin **taxonomie** ne s'applique qu'à la biologie non, qu'entends-tu par là (je connais mal ce mot)? Pour la relation sémantique, oui. 

**Après une discussion avec @Frosty-Z** sur [Gitter](https://gitter.im/sveinburne/lets-play-science), on s'est accordé pour dire que **lien** et **relation** étaient trop proches et prêtaient à confusion. On propose : **appariement** à la place de lien sémantique (matching de noeuds dans l'arbre sémantique) et on garde **relation sémantique** pour l'ontologie.

**Comment by fsamin** [comment]
@sveinburne la taxonomie (taxinomie) vient en effet de la biologie mais s'applique aussi à l'informatique (domaine IA/fouille de données). 

Wikipedia dit :
````
En informatique, le terme taxinomie (taxonomy en anglais) désigne une méthode de
classification des informations dans une architecture structurée de manière évolutive. 
Le terme est couramment employé pour des systèmes de gestion de contenu (CMS).
````

Pour faire simple : un système de classification par "tag" est une taxonomie.

Pour résumer, si on prend l'exemple de github; deux issues peuvent être associées par :
 - les labels : ça c'est une  __taxonomie__  
 - quand on mentionne une issue dans une autre (relation sémantique) : ça c'est une __ontologie__

du moins c'est la représentation que je m'en fais...

**Comment by sveinburne** [comment]
@fsamin Ok pour taxonomie! ça vaudrait la peine qu'on mette une entrée dans la section **Sémantique** des définitions. 

> 
* les labels : ça c'est une taxonomie
* quand on mentionne une issue dans une autre (relation sémantique) : ça c'est une ontologie

C'est bon pour moi. 
Voici la révision que je propose  :

> ~~lien sémantique~~ remplacé par **appariement** : Dans une taxonomie, proximité entre deux items. 
> **appariement fort** : Un **chemin** complet du graphe, soit un **hash sémantique** complet est partagé entre deux items.
> **appariement faible** : Un **sommet** du graphe est partagé entre deux items.

*relation sémantique* est inchangée.

**Comment by Gophys** [comment]
Je pense que ce serait plus simple si vous faisiez des schémas, je me pers un peu dans tout ce que je vous dites et pas sur que vous vous compreniez bien les uns les autres.

**Comment by sveinburne** [comment]
@Gophys Il faut avoir suivit la proposition de **Définitions chaînées** et plus globalement, toute la section **Sémantique** des définitions pour bien suivre je crois ! Mais tu as raison, il y a un besoin d'illustrations / schémas. Je vais essayer de trouver le temps.

**Comment by fsamin** [comment]
@sveinburne c'est parfait ! je suis ok avec ta révision

**Comment by sveinburne** [comment]
**Déplacé dans la PR #73**

**Comment by sveinburne** [comment]
@Gophys, regarde si tu veux bien [la section **Sémantique** revue et reformulée](https://github.com/sveinburne/lets-play-science/blob/lien_semantique_appariement/THE_APP.MD#I.4) qui fait l'objet de la PR #73 et dis nous si c'est plus clair !
