### ISSUE TITLE
Légère modification de l'organisation du repo au 05/12/15

### ISSUE THREAD

**Issue by gossetj** [sveinburne/lets-play-science#60]
Bonjour, on va dire que je suis tatillon, mais il me semble qu'il serait intéressant de renommer les fichiers du repo pour qu'ils soient plus explicites, histoire que ce soit plus évident pour un utilisateur lambda. Par exemple THE APP.md pourrait être Application.md, et SYNTHESE.md serait Synthese-Youtube.md. Je pense également qu'il serait plus compréhensible de séparer les définitions du fichier the APP.md et d'en faire un fichier rien que pour les définitions.

De plus, afin de faciliter l'orientation vers les issues, je propose qu'au lieu d'écrire
[c'est ici : INSPIRATION.MD](https://github.com/sveinburne/lets-play-science/blob/master/INSPIRATION.MD)
on écrive par exemple
on en parle ici: [Forum Inspiration](https://github.com/sveinburne/lets-play-science/issues/32) 
on synthétise ensuite les idées dans le fichier [inspiration.md](https://github.com/sveinburne/lets-play-science/blob/master/INSPIRATION.MD)

Et à la place d'écrire un lien vers une issue unique, qui pourrait se voir fermée, on peut renvoyer vers une liste d'issues avec les labels correspondants. (ce qui me fait penser qu'un rapide tuto sur l'utilisation du filtre des issues peut être intéressant)

**Comment by Frosty-Z** [comment]
Ces remarques me paraissent pertinentes, je dirais juste qu'au lieu de mettre juste "forum inspiration", on pourrait garder "c'est ici : INSPIRATION.MD - [proposer / discuter](https://github.com/sveinburne/lets-play-science/labels/inspiration)" (lien vers la liste des issues labellisées "inspiration")

+1 :+1:  pour le reste

@gossetj N'hésite pas à faire une PR si personne d'autre n'a le temps de traiter :wink:

**Comment by sveinburne** [comment]
@gossetj :+1:, j'avais moi aussi songé à séparer **définitions** de l'application. Et je serais même tenté tant qu'on y est de modifier INSPIRATION.MD en RECHERCHE&INSPIRATION.MD. **Au sujet de l'utilisation des filtres**, il existe déjà un tuto. Mais je suis à 100% pour mettre en lien du README.ME les filtres adéquats. 
**Seul problème** il faudra mettre à jour toutes les références explicites à un fichier. 
@Frosty-Z :+1: pour README.MD

Je propose qu'on termine l'évaluation de ta **PR** #59 avant de faire cette petite restructuration !

**Comment by gossetj** [comment]
@Frosty-Z 
je ne suis qu'en partie d'accord avec ta formulation, car je pense qu'il vaut mieux mettre plus en avant le lien vers les discussions par rapport à la modification, histoire de privilégier les PR réfléchies et limiter les PR à chaud.
@sveinburne 
Effectivement, je n'avais pas vu le tuto. Il semblerait que je sois incorrigible en ce qui concerne les lectures incomplètes.

**Comment by Frosty-Z** [comment]
@gossetj Ok sur ton dernier point

**Comment by sveinburne** [comment]
@gossetj Il n'y a aucun problème, on a tous un peu de `TL;DR;` en nous! On va intégrer tes suggestions en #67 :) 
Donc **consensus tacite** atteint. Je ferme !
