### ISSUE TITLE
Prise de Décision : Consensus tacite et ZenHub

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#62]
Il y a quelques jours, @Frosty-Z faisait allusion à [un groupe de travail dans un projet open-source](https://github.com/thexerteproject/xerteonlinetoolkits/wiki/6.-Decision-Making-Process) qui mettait en pratique un Processus de Décision appelé **Lazy Consensus**.
[Ici la définition qu'il a proposé](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I.3.k), cf #58. Nous avons choisit l'expression **Consensus tacite** ou **implicite** pour marquer l'idée que les **propositions** (par exemple, offres de définition, offre de vision d'ensemble...) sont acceptées tant qu'il y a un **consensus** autour. Pas besoin d'un `+1` explicite, "Silence vaut approbation" ! 

Attention sur le sens d'**approbation**. Dans le cadre d'une offre de définition par exemple, on est sollicité **sur la formulation, la pertinence** de la définition, et pas sur son **implémentation dans l'application**. (cf #54)

**ZenHub** est un outil super méga cool qui s'intègre totalement à **github**. Il nous permet de nous y retrouver plus facilement au niveau de *ce qui doit être évalué par la communauté*. 
Il se présente sous la forme d'un [**plug-in chrome ou firefox**](https://www.zenhub.io/).
Une fois installé sur votre navigateur,  **on peut accorder +1 aux issues et commentaires** : 

![](https://raw.githubusercontent.com/sveinburne/lets-play-science/master/img/plusOne_ZenHub.png)

Mais ça n'est pas tout. Votre menu github doit ressembler maintenant à ça : 
![](https://raw.githubusercontent.com/sveinburne/lets-play-science/master/img/boards.png)
Et en appuyant sur **Board**, voici la vue que vous devriez avoir 
![](https://raw.githubusercontent.com/sveinburne/lets-play-science/master/img/board-ZenHub.png)

Ça devrait pas mal nous aider au niveau du process de décision !
Le choix des "Pipelines" (les blocs du process) et de leur nom est pour le moment arbitraire et pourra évidemment être changé. 
**Qu'en dites-vous?**

**Comment by Frosty-Z** [comment]
C'est très sympa et utile, le seul souci c'est que tout ce qu'offre ZenHub n'est pas présent "par défaut" sur GitHub. Si on décide de s'en servir, il faut donc absolument le signaler très tôt côté ˋReadmeˋ pour que tous les participants actifs soient au courant et l'utilisent.

**Comment by sveinburne** [comment]
@Frosty-Z Oui exact, c'est le seul truc vraiment dommage, que **github** n'ait pas un système de plugin intégré...

**Comment by Aelerinya** [comment]
Je ne suis pas trop pour utiliser des programmes qui se rajoute sur GitHub. Ça augmente encore le nombre d'étapes et de choses à apprendre avant de pouvoir contribuer.
Sinon pour le consensus tacite je suis plutôt pour. Normal qu'on puisse considérer une décision comme acceptée si personne ne s'y est opposé après un certain temps ^^

**Comment by sveinburne** [comment]
@Aelerinya Pour moi, voici ce qu'il y a dans la balance : 
**Plus**
- Fait que les *issues* peuvent avoir un état (en cours, validé), comme ça d'un seul clic sur `Board` tu vois là ou il faut participer, s'il faut aider un nouveau venu etc... ! 
- Intégration propre et "seamless" à **github**
**Moins**
- Nécessite un plugin 

Tu as raison, ça rajoute une petite interface à apprendre (pas bien compliquée tout de même, c'est juste une manière de visualiser les *issues* dans des cases). Mais je trouve que ça rapporte plus que ça ne coûte!

**Comment by Frosty-Z** [comment]
@Aelerinya on peut participer aux specs/réflexions (et même au dev plus tard) en ouvrant des issues et des PR sans problème, sans ZenHub.

Ce plugin apporte un "plus" mais n'est heureusement pas indispensable pour participer disons ponctuellement.

Par contre ZenHub répond bien à certains besoins pour améliorer la productivité d'une équipe de dev, sans qu'il y ait besoin d'une ou plusieurs outils séparés supplémentaires, copier/coller des infos sans arrêt... et ça c'est bien. Et on n'a pas mieux. Et même si c'est un plugin additionnel, ça s'installe en 3 clics et une saisie de son password GitHub, donc pas si difficile d'accès (genre créer un compte sur une autre plateforme, switcher de plateforme sans arrêt...)

**Comment by fsamin** [comment]
@Frosty-Z, je ne connaissais pas ZenHub et je dois dire que c'est assez bluffant !
Je le garde précieusement sous le coude, pour mes autres projets :+1:

**Comment by sveinburne** [comment]
**Consensus tacite atteint (72h)**. Il faudra mettre à jour le README.MD et intégrer tout ça. Expliquer un peu le workflow etc... donc je ne ferme pas tout de suite, on attend d'avoir explicité ça pour les nouveaux venus.
