### ISSUE TITLE
Utiliser des noms de fichier en minuscule

### ISSUE THREAD

**Issue by PifyZ** [sveinburne/lets-play-science#66]
Bonjour,

ne serait-il pas préférable d'utiliser des fichiers avec des noms en minuscule (extension comprise) ?

**Comment by sveinburne** [comment]
Je n'y vois pas d'intérêt en particulier, j'aime bien les lettres capitales, sauf dans les mails, les SMS et les topics ahah. Mais pour des noms de fichiers, boh. Donc je ne suis pas fondamentalement opposé à ce que l'on passe à des lettres minuscules - par contre ça va briser de nombreux liens, donc ça doit être fait dans le cadre de #67 - mais je ne suis pas fondamentalement pour. Vu que ça réclame un coût en édition de vérification de liens morts, je suis plutôt contre.

**Comment by Frosty-Z** [comment]
Plutôt contre pour les mêmes raisons (rapport coût/intérêt très faible).
