### ISSUE TITLE
Readme.md - Utiliser le mot "dépôt" au lieu de "repo / repository" pour les non-initiés

### ISSUE THREAD

**Issue by mathgag555** [sveinburne/lets-play-science#68]
Suggestion : 
Dans le Readme.md, il serait préférable d'utiliser le mot "dépôt" au lieu de "repo / repository" pour les non-initiés, ou au moins le citer à un endroit pour dire ce que c'est un "repo".

**Comment by sveinburne** [comment]
On va attendre 24h, à moins qu'on arrive à cinq votes "+1" avec [ZenHub](https://github.com/sveinburne/lets-play-science/issues/62)

**Comment by gossetj** [comment]
+1

**Comment by Frosty-Z** [comment]
PR #70 créée en ce sens. Merci de vérifier si la définition de "dépôt" que j'ai mise vous convient

> Ensemble de fichiers constituant le code source (+ documentations, éléments graphiques...) d'un projet, généralement accessible via un service de gestion de source (git, SVN, etc.).
> 
> Sur ce site ([GitHub.com](https://github.com)), les **dépôts** sont également associés à diverses fonctionnalités complémentaires telles qu'un gestionnaire de bugs (issues), détourné en **forum** pour le cas de notre **dépôt lets-play-science**.
> 
> Un **dépôt** est également appelé couramment **repository** ou **repo**.

**Comment by sveinburne** [comment]
Ça me va, j'ai accepté la PR car au pire on pourra changer la définition à posteriori! 
Peut-être rajouter une ligne sur le **versionnement**, expliquer rapidement qu'un *service de gestion de source* permet de gérer les multiples versions d'un *projet* (**pas nécessairement de code source**). Mais je ne vais pas pinailler !

**Comment by Frosty-Z** [comment]
Ok j'ai rajouté un lien sur *service de gestion de source* vers l'article Wikipedia https://fr.wikipedia.org/wiki/Logiciel_de_gestion_de_versions

Je me permets de fermer l'issue :wink:
