### ISSUE TITLE
Versionnement sémantique

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#69]
### Question importante : cette définition est-elle claire pour les non informaticiens ?
> ## Versionnement Sémantique
> **[Sens 1.]** : [Spécification officielle](http://semver.org/lang/fr/) de la **V2.0**. En génie logiciel, versionnement au format **MAJEUR**.**MINEUR**.**CORRECTIF**, par exemple **1.0.1** avec : 
>
1. **MAJEUR** : le numéro de version MAJEUR est incrémenté (augmenté de 1) s'il y a des changements rétro-incompatibles
2. **MINEUR**, le numéro de version MINEUR est incrémenté s'il y a des changements rétro-compatibles
3. **CORRECTIF**, le numéro de version de CORRECTIF est incrémenté s'il y a des corrections d’anomalies (bugs) rétro-compatibles
>
**[Sens 2.]** : S'applique à un *document versionné*, avec une signification analogue à [1.]. Versionnement au format **MAJEUR**.**MINEUR**.**CORRECTIF**, par exemple **1.0.1** avec : 
>
1. **MAJEUR**, le numéro de version MAJEUR est incrémenté (augmenté de 1) si le document est fondamentalement restructuré, si son approche est sensiblement remise en question. On appelle le passage à la prochaine version majeure une **Refonte**.
2. **MINEUR**, le numéro de version MINEUR est incrémenté s'il y a des ajouts significatifs mais ne remettant pas en cause les grandes lignes abordées par le document. On appelle le passage à la prochaine version mineure une **Amélioration**.
3. **CORRECTIF**, le numéro de version de CORRECTIF est incrémenté s'il y a des corrections de syntaxe, de mise en page ou d'orthographe. On appelle le passage à la prochaine version de correctif une **Correction**.

*Exemple* : passage de la version **1.0.1** à la version **1.0.2** suite à la correction de petites fautes de syntaxe. 

**Intérêts ?** 
- Cela permet d'un coup d’œil à la communauté de **savoir si le document versionné à été modifié depuis la dernière consultation et dans quelles proportions.** 
- Cela permet à [l'**hôte**](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I.5.f) et à l'**amendeur** de communiquer implicitement sur l'étendue d'un [**amendement**](https://github.com/sveinburne/lets-play-science/blob/master/THE_APP.MD#I.5.h).  

Si on souhaite extrapoler à une fonctionnalité concrète, on pourrait imaginer par exemple dans une interface graphique, un bouton pour valider les modifications suivant le type (dans le même ordre) :

1. Refondre
2. Améliorer
3. Corriger

**PS** : *document* se veut ici être un peu plus générique que *post*. C'est une production de texte versionnée quelconque.

**Comment by Frosty-Z** [comment]
+1 pour cette proposition de définition

**Comment by sveinburne** [comment]
**Consensus tacite atteint**.
