### ISSUE TITLE
Une autre question qu'il faudrait se poser.

### ISSUE THREAD

**Issue by akka-vodol** [sveinburne/lets-play-science#7]
Bonjour à tous.
Pour l'instant ce document parle des différentes méthodes de coopération : comment réunir, filtrer et organiser les posts de manière efficace. Je pense qu'il faudrait aussi se poser la question, en plus des méthodes, des objectifs de la coopération.
Il y a plusieurs aspects à la réalisation d'un let's play science : idées de réponse, recherche, résumé des informations, bilan, et bien sur réalisation de la vidéo. Jusqu'à présent la communauté se contentait de donner les idées, de faire un peu de recherche, et c'est Léo qui faisait le reste. On pourrait se demander si la communauté ne pourrai pas faire plus que ça. Par exemple, on pourrait charger les gens de réunir toutes les sources qu'ils trouvent sur un sujet. D'autres personnes pourraient lire ces sources, et les résumer. Avec suffisamment de personnes et de sources, on pourrait construire un résumé fiable et vérifié sur le sujet en question.
Il faudrait donc se poser la question des différends rôles que la communauté peu jouer. Je propose qu'une section à ce sujet soit ajoutée au projet.

**Comment by sveinburne** [comment]
C'est effectivement un aspect très intéressant que tu soulèves et que j'ai pas relevé dans les commentaires, mais bon j'ai du en lire 20, 30% à peine. As-tu observé des commentaires qu'on pourrait regrouper, qui sont dans cette optique ?

**Comment by fsamin** [comment]
:+1: 

Un post (commentaire sur Youtube) peut être de nature diverses et variées:
 - simple commentaire (ex: pour dire merci)
 - nouvelle idée
 - source
 - hypothèse
 - synthèse 
 - ...

Un post va peut également interagir directement ou indirectement avec tout ou partie des autres commentaires.

L'idée de la carte mentale (heuristique #5 ) est de pouvoir regrouper les posts, les uns par rapport aux autres, les uns avec les autres et de caractériser ces interactions. On pourrait imaginer que Léo pose un sujet et laisse à la communauté le soin de poser des hypothèses, puis des sources... La carte mentale est juste là pour naviguer, visualiser et faire vivre les associations d'idées. 

On peut aussi imaginer que la communauté peut elle même procéder aux regroupements et la manipulation de la carte, ou que cela est le rôle de Léo.

Au sens strict, une carte mentale est sensée représenter le cheminement associatif de la pensée... l'exercice est donc de trouver le moyen de représenter et mettre en évidence le cheminement associatif d'une pensée collective.

**Comment by akka-vodol** [comment]
La carte mentale est effectivement un très bon outil pour suivre l'évolution de la réflexion. Je pense qu'il faudrait essayer de préciser ce concept. Personnellement je n'ai pas le temps, mais si quelqu'un pouvait effectuer plus de recherche là dessus et voir ce qui peut être fait, ça serait bien.
Le concept serait alors qu'une fois que les idées de base ont été trouvées, rassemblées et résumées, les participants peuvent voir ce qui peut être fait pour aller plus loin, et développer la question. On peut aussi imaginer qu'un utilisateur appelle les autres à compléter/approfondir une branche, comme je l'ai fais ci-dessus. Peut-être qu'un système de "marquer comme intéressant" permettrait de repérer les sujets méritant le plus de travail, et de les indiquer aux utilisateurs.

**Comment by akka-vodol** [comment]
Reste encore la question des limites du rôle que les internautes peuvent jouer. Par exemple, si ils confirment une information, celle ci pourra-elle être considérée comme fiable. Si oui, ce serait très puissant, car alors les internautes généreraient une documentation grande et vérifiée sur un sujet. Cependant, cette fiabilité n'est pas certaine, entre-autre parce qu'il n'y a pas tant de monde que ça qui participe à let's play science.
Une autre question qui reste à se poser est si les internautes peuvent faire des choix sur l'orientation de la question. Dans les let's play science précédents, Léo à choisi sur quels sujets se concentrer quand la question était trop vaste, et il à parfois choisi un nouvel angle pour approcher un problème qui n'était pas forcément l'angle de départ. La communauté pourrait-elle faire ces choix seule? Si oui, comment? Cela fait partie des problèmes qui restent à traiter.

**Comment by sveinburne** [comment]
Merci de faire la synthèse de ces réflexions dans une PR sur THE_APP.MD, cf #11 ;)

**Comment by sveinburne** [comment]
Proposition reprise dans #36
