### ISSUE TITLE
Publier les .MD sous forme de site avec pages HTML, plus accessible

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#72]
Reprise de la proposition formulée dans l'issue #71 :

> Utiliser la fonctionnalité de [Pages GitHub](https://pages.github.com/) basée sur le projet [Jekyll](http://jekyllrb.com/) pour voir si on peut publier les .MD en HTML de manière plus lisible et accessible que directement dans GitHub (proposé par @sveinburne au cours d'une discussion privée)

Si on y parvient, cela nécessitera également de modifier le `README` pour rediriger les nouveaux venus vers ce site.

**Comment by sveinburne** [comment]
**Consensus tacite atteint**. On va travailler là dessus une fois la restructuration #67 achevée.

**Comment by Frosty-Z** [comment]
@sveinburne copie de mon message sur le t'chat :
> Concernant les pages statiques, une option intéressante me parait un hébergement + nom de domaine gratuit tout de même sur GitHub pages, avec comme nom de domaine **dirtylab.github.io**
> Si tu es ok, il faudrait créer un repo au niveau de l'organisation "dirtylab" qui porte exactement ce nom (**dirtylab.github.io**). Voir : https://help.github.com/articles/user-organization-and-project-pages/

Ensuite je regarderai comment faire une moulinette qui :
* récupère le contenu de ce repo **sveinburne/lets-play-science** (pourquoi pas à terme utiliser un webhook et héberger la moulinette sur un hébergement mutualisé gratuit, mais dans un deuxième temps je pense)
* réorganise les fichiers pour correspondre à ce qu'attend Jekyll
* mette à jour les fichiers sur le repo **dirtylab/dirtylab.github.io**

**Comment by Frosty-Z** [comment]
Copie du t'chat :

------------------------------------

Bon j'ai tenté une moulinette pour convertir automatiquement les .MD en .html (utilisant grip), corriger autant que possible les liens, et pousser l'ensemble sur le repo github **dirtylab/dirtylab.github.io** ce qui permet d'avoir un site statique sur http://dirtylab.github.io
résultat pas fantastique par rapport à l'effort fourni
ça a au moins le mérite de virer l'interface GitHub tout autour du `README` (reste un "cadre" autour du contenu qui pourrait probablement être viré assez facilement avec quelques directives de style, mais ça risque d'être un peu prise de tête quand même, vu ce que permet **grip** et ce qu'on obtient avec)
à part ça, pas de navigation globale, pas d'entête / pied de page globaux (en tout cas pas faciles à mettre en place)

Pour simplifier tout ça et permettre plus de "souplesse" en termes de fonctionnalités pour le site statique, il faudrait presque bosser directement dans **dirtylab/dirtylab.github.io**, en respectant l'architecture que demande **Jekyll** (par ex. mettre les **.MD** dans un dossier **_include** et faire un `README.MD` succinct à la racine qui redirige directement vers http://dirtylab.github.io)
(enfin je dis pas qu'on va le faire hein, ça va rajouter de la complexité ailleurs, par ex. ça ferait un repo pour les issues, un repo pour le code)
mais vu la relative difficulté et surtout les limitations (moulinette spécifique, limites de **grip** et **Jekyll**), c'est pour le moment une des seules possibilités qui me vient à l'esprit (permettant de garder le travail fourni en **.MD** et avec des possibilités de "templating" minimales : navigation, header, footer)

**Comment by Frosty-Z** [comment]
Je pense qu'on pourrait tout de même, dans nos futures communications, mettre en avant comme "page d'accueil" http://dirtylab.github.io, par contre il faut bien mettre en évidence dans le `README.MD` un lien clair vers ce repo **sveinburne/lets-play-science** du coup...

Des avis, remarques sur tout ça ?

**Comment by Frosty-Z** [comment]
J'aurais peut être une idée d'adaptation de ma "moulinette" pas trop lourde pour que la conversion .MD => .html soit faite par **Jekyll**, ce qui permettrait plus de souplesse (nav / header / footer / CSS...) que si la conversion est faite au préalable par **grip** (qui donne des .html "jolis" mais "ingérables" ensuite).

Je vais creuser ça et je posterai à nouveau dans cette issue si j'arrive à valider cette approche.

**Comment by Frosty-Z** [comment]
Suite à mes dernières modifs / corrections, on peut considérer que c'est fait.

Par contre avant de fermer je pense qu'il faudrait traiter ceci (copier-coller du tchat) :

> Si ce site statique nous sert de vitrine un jour, il faudra peut être songer à modifier la "présentation" au début du `README.MD` (vu qu'on arrive sur un site et non un repo GitHub) ou faire une page d'accueil spécifique genre `INDEX.MD`

**Comment by Frosty-Z** [comment]
Dernier point évoqué repris dans l'issue #89 => je ferme celle ci
