### ISSUE TITLE
VE : Suivre le chemin tracé par la synthèse des commentaires YouTube (Frosty-Z)

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#75]
File de discussion sur la vision d'ensemble :

> Vision d'Ensemble de [Frosty-Z](https://github.com/Frosty-Z)
> ==
> Titre : Suivre le chemin tracé par la [synthèse des commentaires Youtube](../SYNTHESE_YOUTUBE.MD)
> -

> Principe
> -

> Se servir au maximum des **besoins recensés** à la lecture des **commentaires Youtube**, en triant les besoins par le nombre d'occurrences de leur formulation (comme si chaque participant avait *voté* pour les besoins qu'il a exprimé), de nombreux besoins identiques ou très similaires étant exprimés très souvent.

> La **proportion d'occurrences** de chaque besoin (ou sous-besoin) servirait également à déterminer la *priorité* à consacrer à chaque besoin.
Il serait bien entendu possible de travailler sur plusieurs besoins en parallèle (seul ou à plusieurs), en veillant à ne pas trop s'écarter des **proportions exprimées**, en terme de *temps passé* ou *quantité de ressources* consacrés.

[Lire la suite...](https://github.com/sveinburne/lets-play-science/blob/master/PRATIQUE/VE/VE-Frosty-Z.MD)

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#8
