### ISSUE TITLE
VE : La foule a les pleins pouvoirs (Gophys)

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#76]
File de discussion sur la vision d'ensemble :

> Vision d'Ensemble de [Gophys](https://github.com/Gophys)
> ==
> Titre : La foule a les pleins pouvoirs
> -

> Principe
> -
> **La foule** est un ensemble d'individus, avec chacun une volonte, une experience, une histoire, des connaissances etc...
> Dans le but de pouvoir faire collaborer tout le monde ensemble, il est necessaire de creer une **hierarchie** pour  maintenire une cohesion de groupe. Cette vision d'ensemble propose d'avoir une **hierarchie horizontale**. 
> Tout individu, quel qu'il soit est l'egal des autres individus de la foule et son avis est tout aussi important, quel que soit son passe.

[Lire la suite...](https://github.com/sveinburne/lets-play-science/blob/master/PRATIQUE/VE/VE-Gophys.MD)

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#7
