### ISSUE TITLE
Les Visions Partielles (VP)

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#77]
**MÉTA-TOPIC :** Fil de discussion sur les [Visions Partielles](https://github.com/sveinburne/lets-play-science/blob/master/PRATIQUE/VISIONS.MD#II).

Ce fil de discussion permet de parler de la structuration des **visions partielles** et de leur rôle. 

**Extrait** 
> Une **vision partielle** est une proposition d'une ou plusieurs fonctionnalités, sans forcément chercher à couvrir tous les besoins d'une plateforme idéale et ses différents espaces (forum, t'chat, etc.), contrairement à la **vision d'ensemble**.

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#6
