### ISSUE TITLE
VP : Fonctionnalités pour forum - propositions YouTube (multiples auteurs)

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#78]
Fil de discussion pour la **vision partielle** :

> Propositions extraites de commentaires Youtube
> ==============================================

> Dès la création de ce dépôt GitHub, [Jules Randolph](https://github.com/sveinburne) a agrégé et organisé des propositions
de fonctionnalités issues de commentaires Youtube, concernant essentiellement un **espace de discussion de type forum**.

> En théorie, il faudrait créer une VP par proposition listée ci dessous. Par souci de simplicité et accessibilité (il faudrait créer 15-20 fichiers et la plupart de ces propositions sont relativement courtes), elles sont réunies dans ce seul fichier.

[Lire la suite...](https://github.com/sveinburne/lets-play-science/blob/master/PRATIQUE/VP/VP-forum-propositions-Youtube.MD)

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#5
