### ISSUE TITLE
Inception et récursivité

### ISSUE THREAD

**Issue by gossetj** [sveinburne/lets-play-science#79]
En repensant au fait qu'on tentait ici d'obtenir un moyen efficace de collaboration tout en nous appuyant nous-même sur la collaboration sur un système de collaboration, je me suis dit: " **Inception !!!** ". En effet, notre présente collaboration s'inscrit elle même dans la collaboration d'envergure qu'on appelle "société". Ce qui me fait penser pour le coup au principe de **récursivité** nottament utilisé en algorithmie. Ce dernier consiste en une tâche s'appelant elle-même, à deux trois paramètres prêts, créant ainsi un flux de tâches potentiellement "infini". 

C'est pour celà qu'il me semble intéressant de se pencher non seulement sur le concept de collaboration, mais également sur l'interaction des collaborations, tout aussi importante. Autrement dit, essayer de faire autant attention aux collaborations directes entre deux individus qu'aux collaborations mondiales, réussissant à faire avancer des milliards d'individus dans une même direction (bonne ou mauvaise là n'est pas la question ^^). Par là je n'entends pas des mesures ciblées employées ici ou là, mais des plans d'ensemble à priori denses, flous, et conscient ou inconscient.
(Cela renvoie d'ailleurs à un autre problème: dans quelle circonstance un individu a-t-il besoin de connaître le plan global pour le mettre en oeuvre, et dans quelle proportion?)

**Comment by sveinburne** [comment]
Tout à fait! C'est une sorte de régression infinie
![](https://s3.amazonaws.com/com.mirrorproject.photos/2002/04/20/5879-17904.jpg)
Et ça cause parfois des difficultés à cerner ce que l'autre a à l'esprit. C'est pourquoi, idéalement, on devrait toujours préciser bien si on parle de l'application idéale ou des outils actuels à *notre* collaboration. 

> C'est pour celà qu'il me semble intéressant de se pencher non seulement sur le concept de collaboration, mais également sur l'interaction des collaborations, tout aussi importante.

On devrait sans problème pouvoir trouver une problématique (cf la nouvelle structure sur la branche [reorganisation-2](https://github.com/sveinburne/lets-play-science/tree/reorganisation-2), THEORIE/PISTES.MD, qui reprend ton idée! J'avais aussi à l'idée mais j'ai pas eu le temps de le proposer, que **certains défis puissent être des sous défis d'autres communautés**. Bref, que les communautés puissent former un maillage interagissant plutôt qu'être cloisonnés en silos hermétiques.

**Comment by sveinburne** [comment]
@gossetj 
> dans quelle circonstance un individu a-t-il besoin de connaître le plan global pour le mettre en oeuvre, et dans quelle proportion?

à compter que le **défi** appelle une solution, et un plan d'action, auquel cas il s'agit implicitement d'un projet. Il peut aussi s'agir d'une question ouverte qui n'exige pas *une* réponse, mais plus de l'**exploration**. 
Comme par exemple "Quel serait le système politique idéal?". 

Par individu, tu parles d'un **membre** de la communauté?

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#3

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#4
