### ISSUE TITLE
Proposition de nom pour notre communauté : DirtyLab

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#82]
@Frosty-Z et moi on a un peu pris les devants en choisissant **DirtyLab**. Le besoin était essentiel pour nous de distinguer la communauté de **LPS** de la notre, qui se rejoignent sur beaucoup de points mais qui sont par nature dissociables. 
**DirtyLab** a pour seule vocation de réfléchir et expérimenter la collaboration à 5000 !

Êtes vous OK avec ce nom?

Lorsqu'on aura un consensus sur le nom, je m'occuperais (dans un premier temps) des comptes twitter et fb.

**Comment by aurelBZH** [comment]
moi ca me va .

**Comment by Frosty-Z** [comment]
Ok +3 côté ZenHub, je pense qu'on est plutôt bien partis pour ce nom :wink:

**Comment by sveinburne** [comment]
Cosensus tacite, on valide!
