### ISSUE TITLE
Créer et alimenter des comptes Twitter / Facebook

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#83]
Suite à une question de @gossetj sur l'amélioration du premier contact pour les nouveaux venus, @sveinburne a suggéré la création de comptes **Twitter** et **Facebook** pour permettre de visualiser rapidement l'historique du projet (issue #71).

Ce qui permettrait évidemment au passage, que les abonnés/followers soient informés des avancées significatives, et voient de temps en temps que le projet existe et est actif...

Bref, je reprends cette proposition dans une issue à part pour faire une discussion/suivi spécifique.

Il me semble que @sveinburne tu étais partant pour t'occuper de créer les comptes ? (pas forcément les alimenter, mais les créer serait déjà un bon début :wink: )

**Comment by sveinburne** [comment]
Yes je m'en occupe après les fêtes!

**Comment by sveinburne** [comment]
[Et voici le compte twitter](https://twitter.com/DrtyLab) ! Viendez vous abonnez svp !

**Comment by Frosty-Z** [comment]
Ah la vache "DirtyLab" était déjà pris :cry:

**Comment by sveinburne** [comment]
@Frosty-Z Ouai... en plus le gars a rien posté ! Genre compte vide...

**Comment by sveinburne** [comment]
[Voici la page facebook!](https://www.facebook.com/drtylab/)

**Comment by Frosty-Z** [comment]
Nickel ! Reste à mettre à jour le `README`, et surtout alimenter régulièrement ces comptes en contenu...

D'ailleurs une idée me vient vu qu'on n'est pas loin d'adopter **Slack** : mettre en place un petit adaptateur pour récupérer le contenu des posts **Twitter*** et/ou **Facebook** sur le canal "#annonces" ?

**Comment by Frosty-Z** [comment]
Je pense qu'on peut fermer l'issue ! (je ferme, c'est très facile à rouvrir si besoin...)
