### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by gaelfoppolo** [sveinburne/lets-play-science#85]
Comme proposé dans https://github.com/sveinburne/lets-play-science/issues/84 (Reddit), Slack serait une meilleure alternative que Gitter pour la discussion et le débat.

**Slack** est conçu autour de l’idée du travail en équipe, il permet à tous ceux qui doivent travailler ensemble d’échanger avec des messages, mais aussi des fichiers (images, vidéos). Slack fonctionne autour de l’idée de **channels**, des canaux de diffusions qui peuvent correspondre à des projets ou des thématiques. On peut toujours discuter en privé avec une, deux ou plusieurs autres personnes.

![Slack](https://www.appvizer.fr/rest/service/screenshot/1574)

Ce qui fait la particularité de Slack, c'est la possibilité d'échanger avec des sources d’informations externes, par des connexions que l’on peut créer très simplement avec d’autres services en ligne (Trello, GitHub, etc. [liste disponible ici](https://slack.com/apps)), en plus des messages et des fichiers.

Je pense notamment à Léo et son amour des GIFs.

![Slack](https://media.giphy.com/media/5xtDarDuSKfJ4iRPn2M/giphy.gif)

On peut également créer ses propres commandes (IRC-style).

Slack est [multiplateforme](https://slack.com/downloads) : en plus de sa version web, il existe une application pour Windows, Mac OS X, Linux, iOS, Android et Windows Phone. 

Seul nuage qui pourrait assombrir ce beau ciel bleu : dans sa version gratuite, Slack ne permet de consulter que les 10k derniers messages postés.

À noter, une API assez poussée est disponible et permet de faire beaucoup de choses en plus des fonctionnalités de base.

Concernant l'accès à Slack, de base cela se fait uniquement sur invitation, en effet, on ne voudrait pas que n'importe qui puisse intégrer la team surtout si c'est une entreprise. Grâce à l'API, on peut contourner ça et créer une interface d'auto-invitation. C'est qu'on fait beaucoup de projet collaboratif et open source qui utilisent Slack comme moyen de communication.
Il existe plusieurs projets pour ça, le plus populaire étant [slackin](https://github.com/rauchg/slackin). J'ai également développé une interface plus légère pour des besoins personnels [slack-invite](https://github.com/gaelfoppolo/slack-invite).

**Comment by Frosty-Z** [comment]
@gaelfoppolo Wow, merci pour ta contribution.

J'avais vu passer **Slack** en cherchant des outils (il figure d'ailleurs déjà dans le fichier [OUTILS.MD](https://github.com/sveinburne/lets-play-science/blob/master/PRATIQUE/OUTILS.MD)), il manquait juste un comparatif détaillé entre **Gitter** et **Slack**, ce qui est quasiment fait grâce à ton post.

Le système d'invitation par défaut de Slack pouvant être assez facilement contourné (merci pour l'info), il ne reste plus que la limitation d'historique à 10K messages. Je pense qu'on peut très bien vivre avec, même si on a des pics de fréquentation grâce à des vidéos de Léo (ou autre), le tout étant de bien penser à garder ici une trace des propositions / contributions significatives (au moins dans des issues) avant qu'elles ne disparaissent, comme on le fait déjà actuellement depuis Gitter avant qu'une intervention intéressante ne soit "noyée dans la masse".

Un autre point, il faut voir si l'intégration **GitHub** est aussi bonne qu'avec **Gitter** (super pratique).

Ca ne coûte pas grand chose de créer un espace gratuit sur **Slack** pour tester un peu tout ça avant d'éventuellement "migrer" si on est une majorité à y être favorable. Quelqu'un souhaite s'en occuper ?

Il y aura aussi la question de l'hébergement de la solution d'auto-invitation (**slackin** sur Heroku free ? **slack-invite** sur un espace pages perso Free ?...) qu'il faudra se poser avant une éventuelle migration.

**Comment by gaelfoppolo** [comment]
Concernant le système d'invitation, peut-être sur dirtybiology.com si Léo est d'accord. On peut trouver ailleurs facilement je pense.

Pour la limite, je trouve justement que c'est une force : ça permet de faire avancer le débat, ne pas recycler les idées. Et bien entendu, on garde les idées fortes qu'on synthétise ici.

L'intégration est très poussée, je l'utilise tous les jours : possible de choisir plusieurs repo et par branche. Niveau événement on a les issues, commits, deploy, branch, etc.

![Slack](http://i.imgur.com/ZniDuIA.png)

**Comment by Frosty-Z** [comment]
Bon bah [dirtylab.slack.com](https://dirtylab.slack.com) créé !

Je fais un peu joujou avec pour me faire une idée et j'ai envoyé une invitation à @sveinburne 

@gaelfoppolo n'hésite pas à demander une invitation (vu que pour le moment il n'y a pas de "contournement")

**Comment by gaelfoppolo** [comment]
Oui, je veux bien que tu m'ajoutes (mon email est dispo sur mon profil GitHub).

**Comment by Frosty-Z** [comment]
Ce doit être bon

**Comment by Frosty-Z** [comment]
test

**Comment by Frosty-Z** [comment]
Bon pour moi c'est du tout bon tout ça ! Si personne n'y voit d'inconvénient il va falloir mettre à jour le `Readme.md` et le petit site `github.io` qui va avec.

Je pense que si @sveinburne tu es Ok ce n'est pas la peine d'attendre 3 jours pour un consensus tacite.

**Comment by Frosty-Z** [comment]
Ah si il y a quand même la petite histoire du mécanisme d'auto-invitation...

**Comment by sveinburne** [comment]
Au premier contact, Slack me plait beaucoup, mais le mécanisme d'invitations me dérange. On peut avoir un Slack pour l'équipe de dev, mais ce que j'aime dans Gitter c'est la facilité d'accès depuis un compte Github... pas envie que les gens soit rebutés par l'accès

**Comment by Frosty-Z** [comment]
@sveinburne je viens de tester l'outil d'auto invite proposé par @gaelfoppolo, ça passe sans problème avec une adresse "@free.fr". Je pense qu'on peut partir dessus en indiquant que si ça ne fonctionne pas, ne pas hésiter à demander une invitation manuellement.

Ok pour toi ?

Si c'est bon, il y aurait ensuite :  
* le README + le site statique à mettre à jour
* un message à poser sur le canal principal de Gitter pour indiquer l'URL Slack
* poster l'URL du tchat Slack à droite à gauche (Twitter, subreddit...)

**Comment by Frosty-Z** [comment]
Tout ce que j'ai listé dans mon commentaire précédent est fait, je crois qu'on peut fermer ! (et s'auto-congratuler, en toute modestie !)

**Comment by sveinburne** [comment]
Appel à tous les contributeurs! @Roxtarmy @Gophys @fsamin @PifyZ @Aelerinya @Phacocherman @hantropi @akrib @gossetj @aurelBZH **[Venez sur Slack](http://goo.gl/S1CxQo)!**
