### ISSUE TITLE
Un logo pour DirtyLab

### ISSUE THREAD

**Issue by sveinburne** [sveinburne/lets-play-science#86]
A tous ceux et celles qui seraient motivés pour proposer un logo, idéalement au format svg, manifestez-vous ici! Le logo doit être distribué sous licence Creative Commons.

**Comment by Frosty-Z** [comment]
Pour ne pas "perdre" la proposition de @gaelfoppolo sur le tchat

https://stacksocial.com/sales/freebie-logo-design-by-pm-logos

**Comment by sveinburne** [comment]
This issue was moved to dirtylab/wiki#2
