### ISSUE TITLE
Une charte graphique qui claque pour dirtylab.github.io

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#88]
Avis aux graphistes !

Les feuilles de style + images existantes sont définies sur [**ce repository**](https://github.com/Frosty-Z/dirtylab-site-scripts) (sous répertoire **jekyll-stuff**) ; n'hésitez pas à faire des PR directement dessus.

**Comment by sveinburne** [comment]
Faudrait élaborer un peu plus ce qu'on veut de la navigation! Je verrais bien :
- un menu lateral qui slide 
- un header plus fin et plus sobre, qui intègre des liens vers 
  - reddit
  - slack
  - twitter
  - facebook
  - github
- une navigation par dossier (THEORIE, PRATIQUE, VE, VP....) 
- un hover sur les liens avec une petite description de la page

Puis réfléchir à la navigation mobile

**Comment by Frosty-Z** [comment]
+1 pour tout ça, même si je n'ai pas encore bien réfléchi dans le détail sur la navigation, il y a clairement une bonne marge d'amélioration.

J'aurais également tendance à en parler dans une issue à part même si les deux sont un peu liés (=> #90), et faire encore une autre issue pour le "support mobile" (=> #91), histoire de découper et prioriser un peu les choses, parce que là y a du taf !

**Comment by Frosty-Z** [comment]
déplacé ici : https://github.com/dirtylab/site-scripts/issues/13
