### ISSUE TITLE
Une vraie page d'accueil pour dirtylab.github.io

### ISSUE THREAD

**Issue by Frosty-Z** [sveinburne/lets-play-science#89]
Parce que pour l'instant, comme vu sur Slack, le `README` du dépôt GitHub n'est pas vraiment adapté à un site statique, et donc plutôt déroutant...

@sveinburne tu t'étais proposé je crois pour rédiger une page basique.

A terme une jolie page graphiquement simple (et pourquoi pas ludique) avec quelques "punchlines" (par ex. https://www.meteor.com/, https://atom.io/, etc.)  peut être envisagée... A voir peut être si un jour de sérieux graphistes peuvent se pencher sur le sujet :wink:

**Comment by sveinburne** [comment]
@Frosty-Z  Oui je m'en occupe Lundi au plus tard ! Je suis en déplacement toute la journée de demain

**Comment by Frosty-Z** [comment]
Ok. Si j'ai du temps d'ici là j'essaierai de pondre un truc minimaliste, ça m'aidera à adapter la génération de site statique en intégrant un INDEX.MD. Ensuite je te laisserai adapter / améliorer le contenu, ajouter un joli SVG, etc. ;-)

**Comment by Frosty-Z** [comment]
@sveinburne 
`INDEX.MD` basique créé. Pour le moment je n'ai rien mis en ligne (juste vérifié en local que ça fonctionne), j'attends ton feedback.

**Comment by sveinburne** [comment]
@Frosty-Z Ok nouvelle version avec les objectifs bien reformulés poussée sur le dépot, reste plus qu'à envoyer ça sur le site statique !

**Comment by Frosty-Z** [comment]
fait ! fixé quelques liens + quelques listes "foireuses" qui ne s'affichaient pas correctement sur le site (il faut laisser une ligne vide avant, ou les indenter). Je pense qu'on peut fermer l'issue.
